# Generated by Django 3.0.7 on 2023-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='flag',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
