# Generated by Django 3.0.7 on 2023-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0002_monitortask_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='wait_time',
            field=models.IntegerField(default=600),
        ),
    ]
