# Generated by Django 3.0.7 on 2023-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botend', '0003_monitortask_wait_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatAccountTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('last_publish_time', models.DateTimeField(auto_now=True, null=True)),
                ('last_spider_time', models.DateTimeField(auto_now=True, null=True)),
                ('is_zombie', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WechatArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                ('author', models.CharField(default=None, max_length=255, null=True)),
                ('publish_time', models.DateTimeField(default=None, null=True)),
                ('biz', models.CharField(max_length=50)),
                ('digest', models.CharField(default=None, max_length=255, null=True)),
                ('cover', models.CharField(default=None, max_length=255, null=True)),
                ('pics_url', models.TextField(default=None, null=True)),
                ('content_html', models.TextField(default=None, null=True)),
                ('source_url', models.CharField(default=None, max_length=255, null=True)),
                ('comment_id', models.CharField(default=None, max_length=50, null=True)),
                ('sn', models.CharField(default=None, max_length=50, null=True, unique=True)),
                ('spider_time', models.DateTimeField(default=None, null=True)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='targetauth',
            name='ext',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
