# Generated by Django 3.0.7 on 2023-05-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0004_auto_20230526_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatarticle',
            name='pics_url',
        ),
        migrations.RemoveField(
            model_name='wechatarticle',
            name='spider_time',
        ),
    ]
