# Generated by Django 3.0.7 on 2023-05-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0005_auto_20230527_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatarticle',
            name='comment_id',
        ),
    ]
