# Generated by Django 3.0.7 on 2023-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0006_remove_wechatarticle_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechataccounttask',
            name='last_publish_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
