# Generated by Django 3.0.7 on 2023-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0007_auto_20230601_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=200, null=True)),
                ('cveid', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100, null=True)),
                ('score', models.CharField(default='0', max_length=10)),
                ('severity', models.IntegerField(default=0)),
                ('publish_time', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('solutions', models.TextField(null=True)),
                ('reference', models.CharField(max_length=1000, null=True)),
                ('tag', models.CharField(max_length=200, null=True)),
                ('is_poc', models.BooleanField(default=False)),
                ('is_exp', models.BooleanField(default=False)),
                ('is_verify', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VulnMonitorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=1000, null=True)),
                ('last_spider_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
