# Generated by Django 3.0.7 on 2023-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0008_vulndata_vulnmonitortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulndata',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vulndata',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
