# Generated by Django 3.0.7 on 2023-06-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0010_auto_20230607_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulndata',
            name='reference',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
