# Generated by Django 3.0.7 on 2023-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0011_vulndata_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_id', models.IntegerField()),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                ('author', models.CharField(default=None, max_length=255, null=True)),
                ('publish_time', models.DateTimeField(default=None, null=True)),
                ('content_html', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RssMonitorTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=1000)),
                ('last_spider_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
