# Generated by Django 3.0.7 on 2023-06-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0012_rssarticle_rssmonitortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssmonitortask',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
