# Generated by Django 3.0.7 on 2023-07-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0013_rssmonitortask_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssarticle',
            name='url',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='wechatarticle',
            name='digest',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='wechatarticle',
            name='url',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
