# Generated by Django 3.0.7 on 2024-02-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0014_auto_20230704_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('url', models.CharField(default=None, max_length=2000, null=True)),
                ('author', models.CharField(default=None, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('publish_time', models.DateTimeField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wechatarticle',
            name='source_url',
            field=models.CharField(default=None, max_length=555, null=True),
        ),
    ]
