# Generated by Django 3.1.1 on 2023-09-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0014_auto_20230704_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatarticle',
            name='source_url',
            field=models.CharField(default=None, max_length=555, null=True),
        ),
    ]
