# Generated by Django 3.1.1 on 2024-02-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0015_auto_20240223_1017'),
        ('botend', '0015_auto_20230918_0936'),
    ]

    operations = [
    ]
