# Generated by Django 5.1.6 on 2025-03-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0018_gewechattask_active_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gewechatauth',
            name='is_login',
        ),
        migrations.AddField(
            model_name='gewechatauth',
            name='login_status',
            field=models.IntegerField(default=0),
        ),
    ]
