# Generated by Django 5.1.6 on 2025-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0019_remove_gewechatauth_is_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatarticle',
            name='sn',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
