# Generated by Django 5.2.4 on 2025-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0019_remove_gewechatauth_is_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcAplKeywordPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simc_keyword', models.CharField(help_text='SimC格式关键字', max_length=255)),
                ('apl_keyword', models.CharField(help_text='APL格式关键字', max_length=255)),
                ('description', models.CharField(blank=True, help_text='描述', max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'verbose_name': 'SimC APL关键字对',
                'verbose_name_plural': 'SimC APL关键字对',
                'db_table': 'simc_apl_keyword_pair',
                'unique_together': {('simc_keyword', 'apl_keyword')},
            },
        ),
    ]
