# Generated by Django 5.2.4 on 2025-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0020_simcaplkeywordpair'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simcaplkeywordpair',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='simcaplkeywordpair',
            name='apl_keyword',
            field=models.CharField(help_text='APL格式关键字', max_length=100),
        ),
        migrations.AlterField(
            model_name='simcaplkeywordpair',
            name='simc_keyword',
            field=models.CharField(help_text='SimC格式关键字', max_length=100),
        ),
    ]
