# Generated by Django 5.2.4 on 2025-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0021_alter_simcaplkeywordpair_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simcaplkeywordpair',
            name='simc_keyword',
        ),
        migrations.AddField(
            model_name='simcaplkeywordpair',
            name='cn_keyword',
            field=models.CharField(default=2, help_text='CN关键字', max_length=100),
            preserve_default=False,
        ),
    ]
