# Generated by Django 5.2.4 on 2025-08-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0022_remove_simcaplkeywordpair_simc_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simcaplkeywordpair',
            name='update_time',
        ),
    ]
