# Generated by Django 5.1.4 on 2025-08-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0016_merge_20240223_1044'),
        ('botend', '0020_alter_wechatarticle_sn'),
        ('botend', '0023_remove_simcaplkeywordpair_update_time'),
    ]

    operations = [
    ]
