# Generated by Django 5.2.4 on 2025-08-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0020_alter_wechatarticle_sn'),
        ('botend', '0023_remove_simcaplkeywordpair_update_time'),
    ]

    operations = [
    ]
