# Generated by Django 5.2.4 on 2025-08-08 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0024_merge_20250808_1536'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAplStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='APL标题/标识', max_length=200)),
                ('apl_code', models.TextField(help_text='APL代码内容')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户APL存储',
                'verbose_name_plural': '用户APL存储',
                'db_table': 'user_apl_storage',
            },
        ),
    ]
