# Generated by Django 5.2.4 on 2025-08-11 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0025_useraplstorage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simc_code', models.TextField(help_text='SimC代码内容')),
                ('modified_time', models.DateTimeField(auto_now=True, help_text='修改时间')),
                ('current_status', models.IntegerField(default=0, help_text='当前状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('user', models.ForeignKey(help_text='用户ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SimC任务',
                'verbose_name_plural': 'SimC任务',
                'db_table': 'simc_task',
                'ordering': ['-modified_time'],
            },
        ),
    ]
