# Generated by Django 5.1.4 on 2025-08-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0024_merge_20250807_1039'),
        ('botend', '0025_useraplstorage'),
    ]

    operations = [
    ]
