# Generated by Django 5.2.4 on 2025-08-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0026_simctask'),
    ]

    operations = [
        migrations.AddField(
            model_name='simctask',
            name='name',
            field=models.CharField(default=1, help_text='任务名称', max_length=200),
            preserve_default=False,
        ),
    ]
