# Generated by Django 5.2.4 on 2025-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0027_simctask_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(help_text='关联的SimC任务ID')),
                ('result_file', models.FileField(help_text='结果文件', upload_to='simc_results/')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'verbose_name': 'SimC任务结果',
                'verbose_name_plural': 'SimC任务结果',
                'db_table': 'simc_task_result',
            },
        ),
        migrations.RemoveField(
            model_name='simctask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraplstorage',
            name='user',
        ),
        migrations.AddField(
            model_name='simctask',
            name='user_id',
            field=models.IntegerField(default=1, help_text='用户ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplstorage',
            name='user_id',
            field=models.IntegerField(default=1, help_text='用户ID'),
            preserve_default=False,
        ),
    ]
