# Generated by Django 5.2.4 on 2025-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0028_simctaskresult_remove_simctask_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='用户ID')),
                ('name', models.CharField(help_text='配置名称', max_length=200)),
                ('fight_style', models.CharField(default='Patchwerk', max_length=200)),
                ('time', models.IntegerField(default='40')),
                ('target_count', models.IntegerField(default=1)),
                ('action_list', models.TextField(default='', null=True)),
                ('gear_strength', models.IntegerField(default=93330)),
                ('gear_crit', models.IntegerField(default=10730)),
                ('gear_haste', models.IntegerField(default=18641)),
                ('gear_mastery', models.IntegerField(default=21785)),
                ('gear_versatility', models.IntegerField(default=6757)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'verbose_name': 'SimC配置',
                'verbose_name_plural': 'SimC配置',
                'db_table': 'simc_profile',
            },
        ),
        migrations.DeleteModel(
            name='SimcTaskResult',
        ),
        migrations.RemoveField(
            model_name='simctask',
            name='simc_code',
        ),
        migrations.AddField(
            model_name='simctask',
            name='result_file',
            field=models.CharField(help_text='任务结果', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='simc_profile_id',
            field=models.IntegerField(default=1, help_text='用户ID'),
            preserve_default=False,
        ),
    ]
