# Generated by Django 5.2.4 on 2025-08-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0029_simcprofile_delete_simctaskresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcprofile',
            name='talent',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
