# Generated by Django 5.1.4 on 2025-08-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0026_merge_0024_merge_20250807_1039_0025_useraplstorage'),
        ('botend', '0030_simcprofile_talent'),
    ]

    operations = [
    ]
