# Generated by Django 5.2.4 on 2025-08-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0030_simcprofile_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='simctask',
            name='task_type',
            field=models.IntegerField(default=1, help_text='任务类型：1=常规模拟，2=属性模拟'),
        ),
    ]
