# Generated by Django 5.2.4 on 2025-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0031_simctask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simctask',
            name='ext',
            field=models.CharField(blank=True, help_text='扩展信息', max_length=500, null=True),
        ),
    ]
