# Generated by Django 5.2.4 on 2025-08-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0034_alter_simctask_result_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_content', models.TextField(help_text='模板内容')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'verbose_name': 'SimC模板',
                'verbose_name_plural': 'SimC模板',
                'db_table': 'simc_template',
            },
        ),
    ]
