# Generated by Django 5.1.4 on 2025-08-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0031_merge_20250815_1513'),
        ('botend', '0034_alter_simctask_result_file'),
    ]

    operations = [
    ]
