# Generated by Assistant on 2025-11-10

from django.db import migrations, models
import django.utils.timezone


def set_default_for_null_publish_time(apps, schema_editor):
    WowArticle = apps.get_model('botend', 'WowArticle')
    from django.utils import timezone
    now = timezone.now()
    WowArticle.objects.filter(publish_time__isnull=True).update(publish_time=now)


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0035_simctemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowarticle',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.RunPython(set_default_for_null_publish_time, migrations.RunPython.noop),
    ]