# Generated by Django 5.1.4 on 2025-08-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0035_merge_20250818_1617'),
        ('botend', '0035_simctemplate'),
    ]

    operations = [
    ]
