# Generated by Django 5.2.4 on 2026-04-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0036_alter_wowarticle_publish_time_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='WclAnalysisTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcl_url', models.CharField(help_text='WCL原始链接', max_length=2000)),
                ('report_code', models.CharField(blank=True, help_text='WCL报告ID', max_length=128, null=True)),
                ('fight_id', models.CharField(blank=True, help_text='Fight ID', max_length=64, null=True)),
                ('access_token', models.CharField(help_text='公开报告访问令牌', max_length=64)),
                ('status', models.IntegerField(default=0, help_text='状态 0待处理 1处理中 2成功 3失败')),
                ('error_message', models.CharField(blank=True, help_text='错误信息', max_length=1000, null=True)),
                ('source_snapshot_file', models.CharField(blank=True, help_text='源数据快照文件', max_length=255, null=True)),
                ('report_html_file', models.CharField(blank=True, help_text='最终报告HTML文件', max_length=255, null=True)),
                ('summary', models.CharField(blank=True, help_text='摘要', max_length=1000, null=True)),
                ('benchmark_unavailable', models.BooleanField(default=False, help_text='排行榜基准是否不可用')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WCL分析任务',
                'verbose_name_plural': 'WCL分析任务',
                'db_table': 'wcl_analysis_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
