# Generated by Django 5.1.4 on 2025-11-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0036_alter_wowarticle_publish_time_default'),
        ('botend', '0036_merge_0035_merge_20250818_1617_0035_simctemplate'),
    ]

    operations = [
    ]
