# Generated by Django 5.1.4 on 2026-04-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0037_merge_20251110_1758'),
        ('botend', '0037_wclanalysistask'),
    ]

    operations = [
    ]
