# Generated by Django 5.2.4 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0037_wclanalysistask'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcprofile',
            name='spec',
            field=models.CharField(default='fury', help_text='专精标识，如 fury/arms/fire', max_length=100),
        ),
        migrations.AddField(
            model_name='simctemplate',
            name='spec',
            field=models.CharField(default='default', help_text='模板适配专精，如 fury/arms/default', max_length=100),
        ),
    ]
