# Generated by Django 5.1.4 on 2026-04-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0038_merge_0037_merge_20251110_1758_0037_wclanalysistask'),
        ('botend', '0039_alter_gewechatauth_id_alter_gewechatroomlist_id_and_more'),
    ]

    operations = [
    ]
