# Generated by Django 6.0.4 on 2026-04-24

from django.db import migrations, models


def seed_fury_rule(apps, schema_editor):
    Rule = apps.get_model('botend', 'SimcSecondaryStatRule')
    Rule.objects.get_or_create(
        spec='fury',
        defaults={
            'crit_per_percent': 46,
            'haste_per_percent': 44,
            'mastery_per_percent': 46,
            'mastery_coefficient': 1.4,
            'versatility_per_percent': 54,
        }
    )


def unseed_fury_rule(apps, schema_editor):
    Rule = apps.get_model('botend', 'SimcSecondaryStatRule')
    Rule.objects.filter(spec='fury').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0039_alter_gewechatauth_id_alter_gewechatroomlist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcSecondaryStatRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(help_text='专精标识，如 fury/arms/fire', max_length=100, unique=True)),
                ('crit_per_percent', models.FloatField(default=46, help_text='暴击每1%所需绿字')),
                ('haste_per_percent', models.FloatField(default=44, help_text='急速每1%所需绿字')),
                ('mastery_per_percent', models.FloatField(default=46, help_text='精通每1%所需绿字（系数前）')),
                ('mastery_coefficient', models.FloatField(default=1.4, help_text='精通系数（最终结果乘以该值）')),
                ('versatility_per_percent', models.FloatField(default=54, help_text='全能每1%所需绿字')),
            ],
            options={
                'db_table': 'simc_secondary_stat_rule',
                'verbose_name': 'SimC绿字转换规则',
                'verbose_name_plural': 'SimC绿字转换规则',
            },
        ),
        migrations.RunPython(seed_fury_rule, unseed_fury_rule),
    ]
