# Generated by Django 5.1.4 on 2026-04-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0040_simcsecondarystatrule'),
        ('botend', '0041_alter_gewechatauth_id_alter_gewechatroomlist_id_and_more'),
    ]

    operations = [
    ]
