# Generated by Django 5.1.4 on 2026-05-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0042_merge_20260424_1618'),
        ('botend', '0042_simcbackendbinary_progress_fields'),
    ]

    operations = [
    ]
