# Generated by Django 4.2.30 on 2026-05-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0043_portalcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=2000)),
                ('url_hash', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='unknown', max_length=32)),
                ('tag', models.CharField(default='', max_length=64)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wow_portal_event',
            },
        ),
        migrations.CreateModel(
            name='PortalMplusRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('dungeon', models.CharField(default='', max_length=128)),
                ('level', models.IntegerField(default=0)),
                ('time_seconds', models.IntegerField(default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('tank', models.CharField(blank=True, max_length=128, null=True)),
                ('healer', models.CharField(blank=True, max_length=128, null=True)),
                ('dps_json', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='unknown', max_length=32)),
                ('region', models.CharField(blank=True, max_length=32, null=True)),
                ('season', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wow_portal_mplus_run',
            },
        ),
        migrations.CreateModel(
            name='PortalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=2000)),
                ('url_hash', models.CharField(max_length=64, unique=True)),
                ('bvid', models.CharField(blank=True, max_length=32, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author_name', models.CharField(default='', max_length=255)),
                ('author_url', models.CharField(default='', max_length=2000)),
                ('tag', models.CharField(default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wow_portal_video',
            },
        ),
        migrations.CreateModel(
            name='VideoMonitorTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=64)),
                ('platform', models.CharField(default='bilibili', max_length=32)),
                ('target_url', models.CharField(max_length=2000)),
                ('target_url_hash', models.CharField(max_length=64)),
                ('last_seen_bvid', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ext_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wow_video_monitor_target',
            },
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='category',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='source',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='url_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='wowarticle',
            index=models.Index(fields=['url_hash'], name='botend_wowa_url_has_5335fa_idx'),
        ),
        migrations.AddIndex(
            model_name='wowarticle',
            index=models.Index(fields=['source'], name='botend_wowa_source_2baa72_idx'),
        ),
        migrations.AddIndex(
            model_name='wowarticle',
            index=models.Index(fields=['category'], name='botend_wowa_categor_9dd84f_idx'),
        ),
        migrations.AddIndex(
            model_name='wowarticle',
            index=models.Index(fields=['publish_time'], name='botend_wowa_publish_b30441_idx'),
        ),
        migrations.AddIndex(
            model_name='videomonitortarget',
            index=models.Index(fields=['tag'], name='wow_video_m_tag_cd8329_idx'),
        ),
        migrations.AddIndex(
            model_name='videomonitortarget',
            index=models.Index(fields=['target_url_hash'], name='wow_video_m_target__055faa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videomonitortarget',
            unique_together={('platform', 'target_url_hash')},
        ),
        migrations.AddField(
            model_name='portalvideo',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botend.videomonitortarget'),
        ),
        migrations.AddIndex(
            model_name='portalmplusrun',
            index=models.Index(fields=['season', 'region'], name='wow_portal__season_eee712_idx'),
        ),
        migrations.AddIndex(
            model_name='portalmplusrun',
            index=models.Index(fields=['dungeon'], name='wow_portal__dungeon_1b5dae_idx'),
        ),
        migrations.AddIndex(
            model_name='portalevent',
            index=models.Index(fields=['url_hash'], name='wow_portal__url_has_e56436_idx'),
        ),
        migrations.AddIndex(
            model_name='portalvideo',
            index=models.Index(fields=['url_hash'], name='wow_portal__url_has_c9803b_idx'),
        ),
        migrations.AddIndex(
            model_name='portalvideo',
            index=models.Index(fields=['tag'], name='wow_portal__tag_ec17ee_idx'),
        ),
        migrations.AddIndex(
            model_name='portalvideo',
            index=models.Index(fields=['published_at'], name='wow_portal__publish_7df307_idx'),
        ),
    ]
