# Generated by Django 4.2.30 on 2026-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0044_portalevent_portalmplusrun_portalvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmplusrun',
            name='run_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
