# Generated by Django 4.2.30 on 2026-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0045_portalmplusrun_run_url_alter_gewechatauth_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmplusrun',
            name='party_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
