# Generated by Django 4.2.30 on 2026-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0046_portalmplusrun_party_json_alter_gewechatauth_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmplusrun',
            name='dungeon_slug',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='portalmplusrun',
            index=models.Index(fields=['dungeon_slug'], name='wow_portal__dungeon_816a01_idx'),
        ),
    ]
