# Generated by Django 4.2.30 on 2026-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0047_portalmplusrun_dungeon_slug_alter_gewechatauth_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalToolLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
                ('url_hash', models.CharField(max_length=64, unique=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_topbar', models.BooleanField(default=False)),
                ('topbar_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wow_portal_tool_link',
                'indexes': [models.Index(fields=['url_hash'], name='wow_portal__url_has_899d84_idx'), models.Index(fields=['is_active'], name='wow_portal__is_acti_0713d1_idx'), models.Index(fields=['is_topbar'], name='wow_portal__is_topb_e1fbd9_idx'), models.Index(fields=['sort_order'], name='wow_portal__sort_or_c80abb_idx')],
            },
        ),
    ]
