# Generated by Django 5.1.4 on 2026-05-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0043_merge_20260506_1708'),
        ('botend', '0048_alter_gewechatauth_id_alter_gewechatroomlist_id_and_more'),
    ]

    operations = [
    ]
