# Generated by Django 4.2.30 on 2026-05-08 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0048_alter_gewechatauth_id_alter_gewechatroomlist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='报警分类，如 WECHAT_COOKIE_EXPIRED/SIMC_UPDATE_FAILED', max_length=64)),
                ('subject', models.CharField(blank=True, default='', help_text='报警主体，如 wechat/api.bilibili.com/win64', max_length=128)),
                ('dedup_key', models.CharField(help_text='去重键 category@subject', max_length=220, unique=True)),
                ('level', models.IntegerField(default=3, help_text='级别 1=info 2=warning 3=fatal')),
                ('title', models.CharField(help_text='标题', max_length=200)),
                ('content', models.TextField(blank=True, default='', help_text='详细信息')),
                ('count', models.IntegerField(default=1, help_text='累计触发次数')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_alert',
                'verbose_name': '系统报警',
                'verbose_name_plural': '系统报警',
            },
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['is_read'], name='system_aler_is_read_4f7a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['category'], name='system_aler_category_b0a3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='systemalert',
            index=models.Index(fields=['last_seen_at'], name='system_aler_last_se_6e9e3e_idx'),
        ),
    ]

