# Generated by Django 5.1.4 on 2026-05-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0049_merge_20260508_1434'),
        ('botend', '0049_systemalert'),
    ]

    operations = [
    ]
