# Generated by Django 4.2.30 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0049_systemalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaltoollink',
            name='icon_path',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]

