# Generated by Django 5.1.4 on 2026-05-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0050_merge_0049_merge_20260508_1434_0049_systemalert'),
        ('botend', '0050_portaltoollink_icon_path'),
    ]

    operations = [
    ]
