# Generated by Django 4.2.30 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0050_portaltoollink_icon_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMythicstatsDpsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='season-mn-1', max_length=64)),
                ('period_id', models.IntegerField()),
                ('period_label', models.CharField(default='', max_length=64)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('dungeon_id', models.IntegerField(default=0)),
                ('dungeon_name', models.CharField(default='', max_length=128)),
                ('role', models.CharField(default='damage', max_length=16)),
                ('rank', models.IntegerField(default=0)),
                ('diff_raw', models.CharField(blank=True, default='', max_length=16)),
                ('diff_value', models.IntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, default='', max_length=4)),
                ('avg_text', models.CharField(blank=True, default='', max_length=32)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('top_text', models.CharField(blank=True, default='', max_length=32)),
                ('top_value', models.FloatField(blank=True, null=True)),
                ('runs_text', models.CharField(blank=True, default='', max_length=32)),
                ('runs_value', models.IntegerField(blank=True, null=True)),
                ('spec_name', models.CharField(default='', max_length=128)),
                ('spec_slug', models.CharField(default='', max_length=128)),
                ('spec_url', models.CharField(default='', max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_portal_mythicstats_dps_row',
                'indexes': [
                    models.Index(fields=['season', 'period_id'], name='wow_portal__season__0c9488_idx'),
                    models.Index(fields=['season', 'period_id', 'dungeon_id', 'role'], name='wow_portal__season__cd7401_idx'),
                    models.Index(fields=['spec_slug'], name='wow_portal__spec_sl_a2b2f9_idx'),
                    models.Index(fields=['updated_at'], name='wow_portal__updated__630be7_idx'),
                ],
                'unique_together': {('season', 'period_id', 'dungeon_id', 'role', 'spec_slug')},
            },
        ),
    ]

