# Generated by Django 4.2.30 on 2026-05-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botend", "0051_portalmythicstatsdpsrow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalmythicstatsdpsrow",
            name="season",
            field=models.CharField(default="unknown", max_length=64),
        ),
    ]

