# Generated by Django 4.2.30 on 2026-05-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0051_portalmythicstatsdpsrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowSkillDiffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='wow', max_length=32)),
                ('locale', models.CharField(default='enUS', max_length=8)),
                ('from_build', models.CharField(max_length=64)),
                ('to_build', models.CharField(max_length=64)),
                ('content_md', models.TextField(blank=True, default='')),
                ('changed_tables_json', models.TextField(blank=True, default='')),
                ('spell_count', models.IntegerField(default=0)),
                ('class_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_skill_diff_report',
                'indexes': [
                    models.Index(fields=['branch', 'locale'], name='wow_skill__branch__b59a5d_idx'),
                    models.Index(fields=['to_build'], name='wow_skill__to_bui_1b98a9_idx'),
                    models.Index(fields=['created_at'], name='wow_skill__created_0f2f07_idx'),
                ],
                'unique_together': {('branch', 'locale', 'to_build')},
            },
        ),
    ]

