# Generated by Django 5.2.13 on 2026-05-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0052_portalmythicstatsdpsrow_season_default'),
        ('botend', '0052_wowskilldiffreport'),
    ]

    operations = [
    ]
