# Generated by Django 5.1.4 on 2026-05-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0051_merge_20260509_1120'),
        ('botend', '0053_merge_20260511_1030'),
    ]

    operations = [
    ]
