# Generated by Django 5.1.4 on 2026-05-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0054_delete_portalcache'),
        ('botend', '0054_merge_20260511_1730'),
    ]

    operations = [
    ]
