# Generated by Django 5.1.4 on 2026-05-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0055_merge_20260511_1816'),
        ('botend', '0055_wowarticle_reply_count'),
    ]

    operations = [
    ]
