# Generated by Django 5.1.4 on 2026-05-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0056_merge_20260511_1821'),
        ('botend', '0058_wow_spell_snapshot_models'),
    ]

    operations = [
    ]
