# Generated by Django 4.2.30 on 2026-05-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0058_wow_spell_snapshot_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowWagoMonitorState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(default='wow', max_length=32)),
                ('locale', models.CharField(default='enUS', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('build', models.CharField(blank=True, default='', max_length=64)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_status', models.CharField(blank=True, default='', max_length=64)),
                ('report_url', models.CharField(blank=True, default='', max_length=500)),
                ('wago_diff_url', models.CharField(blank=True, default='', max_length=500)),
                ('ext', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_wago_monitor_state',
            },
        ),
        migrations.AddIndex(
            model_name='wowwagomonitorstate',
            index=models.Index(fields=['is_active'], name='wow_wago_mo_is_acti_3ac605_idx'),
        ),
        migrations.AddIndex(
            model_name='wowwagomonitorstate',
            index=models.Index(fields=['branch', 'locale'], name='wow_wago_mo_branch_7527dd_idx'),
        ),
        migrations.AddIndex(
            model_name='wowwagomonitorstate',
            index=models.Index(fields=['build'], name='wow_wago_mo_build_a4ae15_idx'),
        ),
        migrations.AddIndex(
            model_name='wowwagomonitorstate',
            index=models.Index(fields=['last_run_at'], name='wow_wago_mo_last_ru_eada7e_idx'),
        ),
        migrations.AddIndex(
            model_name='wowwagomonitorstate',
            index=models.Index(fields=['last_event_at'], name='wow_wago_mo_last_ev_8d9417_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wowwagomonitorstate',
            unique_together={('branch', 'locale')},
        ),
    ]
