# Generated by Django 5.1.4 on 2026-05-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0059_merge_20260512_1805'),
        ('botend', '0059_wowwagomonitorstate_and_more'),
    ]

    operations = [
    ]
