# Generated by Django 4.2.30 on 2026-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0059_wowwagomonitorstate_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalmythicstatsdpsrow',
            new_name='wow_portal__season_cca018_idx',
            old_name='wow_portal__season__0c9488_idx',
        ),
        migrations.RenameIndex(
            model_name='portalmythicstatsdpsrow',
            new_name='wow_portal__season_509105_idx',
            old_name='wow_portal__season__cd7401_idx',
        ),
        migrations.RenameIndex(
            model_name='portalmythicstatsdpsrow',
            new_name='wow_portal__spec_sl_c7428a_idx',
            old_name='wow_portal__spec_sl_a2b2f9_idx',
        ),
        migrations.RenameIndex(
            model_name='portalmythicstatsdpsrow',
            new_name='wow_portal__updated_c6a835_idx',
            old_name='wow_portal__updated__630be7_idx',
        ),
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='system_aler_is_read_94ec77_idx',
            old_name='system_aler_is_read_4f7a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='system_aler_categor_673b10_idx',
            old_name='system_aler_category_b0a3b8_idx',
        ),
        migrations.RenameIndex(
            model_name='systemalert',
            new_name='system_aler_last_se_1e7b5c_idx',
            old_name='system_aler_last_se_6e9e3e_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspecspellmapsnapshot',
            new_name='wow_spec_sp_branch_9e632f_idx',
            old_name='wow_spec_s_branch__fc8c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspecspellmapsnapshot',
            new_name='wow_spec_sp_spec_id_07228e_idx',
            old_name='wow_spec_s_spec_id_0d1b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspecspellmapsnapshot',
            new_name='wow_spec_sp_spell_i_f94f8f_idx',
            old_name='wow_spec_s_spell_id_92f7f7_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspecspellmapsnapshot',
            new_name='wow_spec_sp_updated_eb24a4_idx',
            old_name='wow_spec_s_updated__63b0c4_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspelleffectsnapshot',
            new_name='wow_spell_e_branch_0e793d_idx',
            old_name='wow_spell_e_branch__dc0b4f_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspelleffectsnapshot',
            new_name='wow_spell_e_spell_i_209320_idx',
            old_name='wow_spell_e_spell_id_55c2cb_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspelleffectsnapshot',
            new_name='wow_spell_e_spell_i_49a17b_idx',
            old_name='wow_spell_e_spell_i_6b7e74_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspelleffectsnapshot',
            new_name='wow_spell_e_updated_0a7496_idx',
            old_name='wow_spell_e_updated__f9530c_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspellsnapshot',
            new_name='wow_spell_s_branch_188d53_idx',
            old_name='wow_spell_branch__ed17a0_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspellsnapshot',
            new_name='wow_spell_s_spell_i_dc9311_idx',
            old_name='wow_spell_spell_id_7d8a4d_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspellsnapshot',
            new_name='wow_spell_s_updated_2aece1_idx',
            old_name='wow_spell_updated__530fb4_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspellsnapshotstate',
            new_name='wow_spell_s_branch_c436e1_idx',
            old_name='wow_spell_s_branch__55b8a0_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspellsnapshotstate',
            new_name='wow_spell_s_snapsho_d10194_idx',
            old_name='wow_spell_s_snapshot_4b1cde_idx',
        ),
        migrations.RenameIndex(
            model_name='wowspellsnapshotstate',
            new_name='wow_spell_s_updated_b8278c_idx',
            old_name='wow_spell_s_updated__1b8e6a_idx',
        ),
        migrations.AlterField(
            model_name='gewechatauth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gewechatroomlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gewechattask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitorwebhook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portalmythicstatsdpsrow',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rssarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rssmonitortask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simcaplkeywordpair',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simcprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simcsecondarystatrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simctask',
            name='ext',
            field=models.CharField(blank=True, help_text='扩展信息', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='simctask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simctemplate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='targetauth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraplstorage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vulndata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vulnmonitortask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wclanalysistask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wechataccounttask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wechatarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wowarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wowskilldiffreport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wowspecspellmapsnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wowspelleffectsnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wowspellsnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wowspellsnapshotstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
