# Generated by Django 5.2.13 on 2026-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0060_rename_wow_portal__season__0c9488_idx_wow_portal__season_cca018_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPeakSpecRankRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='unknown', max_length=64)),
                ('region', models.CharField(default='world', max_length=32)),
                ('class_slug', models.CharField(default='', max_length=64)),
                ('class_name', models.CharField(default='', max_length=128)),
                ('spec_slug', models.CharField(default='', max_length=64)),
                ('spec_name', models.CharField(default='', max_length=128)),
                ('spec_role', models.CharField(default='', max_length=16)),
                ('rank', models.IntegerField(default=0)),
                ('character_name', models.CharField(default='', max_length=128)),
                ('character_path', models.CharField(blank=True, default='', max_length=500)),
                ('score', models.FloatField(blank=True, null=True)),
                ('score_color', models.CharField(blank=True, default='', max_length=16)),
                ('rio_region_slug', models.CharField(blank=True, default='', max_length=16)),
                ('realm_slug', models.CharField(blank=True, default='', max_length=64)),
                ('realm_name', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wow_portal_peak_spec_rank_row',
                'indexes': [models.Index(fields=['season', 'region'], name='wow_portal__season_4aa828_idx'), models.Index(fields=['spec_role'], name='wow_portal__spec_ro_b24136_idx'), models.Index(fields=['class_slug', 'spec_slug'], name='wow_portal__class_s_01a045_idx'), models.Index(fields=['updated_at'], name='wow_portal__updated_6a46cf_idx')],
                'unique_together': {('season', 'region', 'class_slug', 'spec_slug', 'rank')},
            },
        ),
    ]
