# Generated by Django 5.1.4 on 2026-05-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0060_merge_20260514_1141'),
        ('botend', '0060_rename_wow_portal__season__0c9488_idx_wow_portal__season_cca018_idx_and_more'),
    ]

    operations = [
    ]
