# Generated by Django 5.1.4 on 2026-05-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0061_merge_20260514_1404'),
        ('botend', '0061_portalpeakspecrankrow'),
    ]

    operations = [
    ]
