# Generated by Django 5.2.13 on 2026-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0062_wowspellsnapshot_name_zh'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMplusSeasonCutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='unknown', max_length=64)),
                ('region', models.CharField(default='world', max_length=16)),
                ('cutoff_0_1', models.FloatField(blank=True, null=True)),
                ('cutoff_1', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='raiderio', max_length=32)),
                ('source_updated_at', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_portal_mplus_season_cutoff',
                'indexes': [models.Index(fields=['season', 'region'], name='wow_portal__season_4197c2_idx'), models.Index(fields=['updated_at'], name='wow_portal__updated_ceff79_idx')],
                'unique_together': {('season', 'region')},
            },
        ),
    ]
