# Generated by Django 5.2.13 on 2026-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0063_portalmplusseasoncutoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('md_path', models.CharField(default='', max_length=500)),
                ('ext_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_daily_report',
                'indexes': [
                    models.Index(fields=['report_date'], name='wow_daily__report__0f1e69_idx'),
                    models.Index(fields=['updated_at'], name='wow_daily__updated_8dfc8c_idx'),
                ],
            },
        ),
    ]

