# Generated by Django 5.1.4 on 2026-05-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0062_merge_20260515_1447'),
        ('botend', '0063_portalmplusseasoncutoff'),
    ]

    operations = [
    ]
