# Generated by Django 5.1.4 on 2026-05-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0064_merge_20260515_1736'),
        ('botend', '0064_wowdailyreport'),
    ]

    operations = [
    ]
