# Generated by Django 5.2.13 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0064_wowdailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='env_limit',
            field=models.IntegerField(default=0),
        ),
    ]

