# Generated by Django 5.2.13 on 2026-05-21 00:00

from django.db import migrations, models
from django.utils import timezone


def backfill_wowarticle_created_at(apps, schema_editor):
    WowArticle = apps.get_model("botend", "WowArticle")
    now = timezone.now()
    for row in WowArticle.objects.all().only("id", "publish_time", "created_at", "updated_at"):
        if getattr(row, "created_at", None):
            continue
        pt = getattr(row, "publish_time", None) or now
        row.created_at = pt
        row.updated_at = pt
        row.save(update_fields=["created_at", "updated_at"])


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("botend", "0065_monitortask_env_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="wowarticle",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="wowarticle",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_wowarticle_created_at, reverse_code=noop),
        migrations.AlterField(
            model_name="wowarticle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="wowarticle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]

