# Generated by Django 5.1.4 on 2026-05-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0065_merge_0064_merge_20260515_1736_0064_wowdailyreport'),
        ('botend', '0065_monitortask_env_limit'),
    ]

    operations = [
    ]
