# Generated by Django 5.2.13 on 2026-05-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0066_wowarticle_created_at_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wowarticle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wowarticle',
            name='updated_at',
        ),
    ]
