# Generated by Django 5.2.13 on 2026-06-02 02:34
# Patched: all index operations made idempotent to handle divergent server state.

from django.db import migrations, models


def _safe_drop_index(schema_editor, table, index_name):
    """Drop an index if it exists, ignore errors."""
    vendor = getattr(schema_editor.connection, "vendor", "")
    try:
        if vendor == "mysql":
            schema_editor.execute(f"DROP INDEX {index_name} ON {table};")
        else:
            schema_editor.execute(f"DROP INDEX IF EXISTS {index_name};")
    except Exception:
        pass


def _safe_create_index(schema_editor, table, columns, index_name):
    """Create an index if it doesn't already exist."""
    vendor = getattr(schema_editor.connection, "vendor", "")
    cols = ", ".join(columns)
    try:
        if vendor == "mysql":
            schema_editor.execute(
                f"CREATE INDEX {index_name} ON {table} ({cols});"
            )
        else:
            schema_editor.execute(
                f"CREATE INDEX IF NOT EXISTS {index_name} ON {table} ({cols});"
            )
    except Exception:
        pass


# --- wow_wago_mo_hotfix_4f52f6_idx ---
def _drop_hotfix_4f52f6_idx(apps, schema_editor):
    _safe_drop_index(schema_editor, "wow_wago_monitor_state",
                     "wow_wago_mo_hotfix_4f52f6_idx")


# --- wow_daily_report indexes ---
def _rename_wow_daily_report_idx(apps, schema_editor):
    _safe_drop_index(schema_editor, "wow_daily_report",
                     "wow_daily__report__0f1e69_idx")
    _safe_create_index(schema_editor, "wow_daily_report",
                       ["report_date"], "wow_daily_r_report__aa83a8_idx")


def _rename_wow_daily_updated_idx(apps, schema_editor):
    _safe_drop_index(schema_editor, "wow_daily_report",
                     "wow_daily__updated_8dfc8c_idx")
    _safe_create_index(schema_editor, "wow_daily_report",
                       ["updated_at"], "wow_daily_r_updated_4ad1fc_idx")


# --- wow_wago_monitor_state indexes ---
def _rename_wow_wago_hotfix_b7502c(apps, schema_editor):
    _safe_drop_index(schema_editor, "wow_wago_monitor_state",
                     "wow_wago_mo_hotfix_b7502c_idx")
    _safe_create_index(schema_editor, "wow_wago_monitor_state",
                       ["hotfix"], "wow_wago_mo_hotfix__6f6a60_idx")


def _rename_wow_wago_hotfix_1118a0(apps, schema_editor):
    _safe_drop_index(schema_editor, "wow_wago_monitor_state",
                     "wow_wago_mo_hotfix_1118a0_idx")
    _safe_create_index(schema_editor, "wow_wago_monitor_state",
                       ["hotfix", "region_id"],
                       "wow_wago_mo_hotfix__f489ff_idx")


def _rename_wow_wago_hotfix_4b8b02(apps, schema_editor):
    _safe_drop_index(schema_editor, "wow_wago_monitor_state",
                     "wow_wago_mo_hotfix_4b8b02_idx")
    _safe_create_index(schema_editor, "wow_wago_monitor_state",
                       ["hotfix", "build_number"],
                       "wow_wago_mo_hotfix__e9b108_idx")


def _rename_wow_wago_hotfix_9a1c2b(apps, schema_editor):
    _safe_drop_index(schema_editor, "wow_wago_monitor_state",
                     "wow_wago_mo_hotfix_9a1c2b_idx")
    _safe_create_index(schema_editor, "wow_wago_monitor_state",
                       ["hotfix", "region_id", "build_number"],
                       "wow_wago_mo_hotfix__10480c_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0074_remove_wowwagomonitorstate_hotfix_build_region'),
    ]

    operations = [
        # 1. Drop hotfix_4f52f6_idx (idempotent)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_drop_hotfix_4f52f6_idx,
                                     migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='wowwagomonitorstate',
                    name='wow_wago_mo_hotfix_4f52f6_idx',
                ),
            ],
        ),
        # 2. Rename wow_daily_report indexes (idempotent: drop old + create new)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_wow_daily_report_idx,
                                     migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wowdailyreport',
                    new_name='wow_daily_r_report__aa83a8_idx',
                    old_name='wow_daily__report__0f1e69_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_wow_daily_updated_idx,
                                     migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wowdailyreport',
                    new_name='wow_daily_r_updated_4ad1fc_idx',
                    old_name='wow_daily__updated_8dfc8c_idx',
                ),
            ],
        ),
        # 3. Rename wow_wago_monitor_state indexes (idempotent)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_wow_wago_hotfix_b7502c,
                                     migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wowwagomonitorstate',
                    new_name='wow_wago_mo_hotfix__6f6a60_idx',
                    old_name='wow_wago_mo_hotfix_b7502c_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_wow_wago_hotfix_1118a0,
                                     migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wowwagomonitorstate',
                    new_name='wow_wago_mo_hotfix__f489ff_idx',
                    old_name='wow_wago_mo_hotfix_1118a0_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_wow_wago_hotfix_4b8b02,
                                     migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wowwagomonitorstate',
                    new_name='wow_wago_mo_hotfix__e9b108_idx',
                    old_name='wow_wago_mo_hotfix_4b8b02_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_wow_wago_hotfix_9a1c2b,
                                     migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wowwagomonitorstate',
                    new_name='wow_wago_mo_hotfix__10480c_idx',
                    old_name='wow_wago_mo_hotfix_9a1c2b_idx',
                ),
            ],
        ),
        # 4. Add new fields
        migrations.AddField(
            model_name='portalmplusseasoncutoff',
            name='cutoff_0_1_prev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalmplusseasoncutoff',
            name='cutoff_1_prev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalmplusseasoncutoff',
            name='prev_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='content_cn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='title_cn',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
