# Generated by Django 5.2.13 on 2026-06-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0074_remove_wowwagomonitorstate_hotfix_build_region'),
    ]

    def _drop_hotfix_4f52f6_idx(apps, schema_editor):
        """
        兼容 SQLite：如果前置迁移在 SQLite 下已提前处理/不存在该索引，默认的 RemoveIndex 会直接报错。
        这里用“尽力而为”的 SQL 删除，保证迁移可重入。
        """
        vendor = getattr(schema_editor.connection, "vendor", "")
        table = "wow_wago_monitor_state"
        try:
            if vendor == "mysql":
                schema_editor.execute(f"DROP INDEX wow_wago_mo_hotfix_4f52f6_idx ON {table};")
            else:
                schema_editor.execute("DROP INDEX IF EXISTS wow_wago_mo_hotfix_4f52f6_idx;")
        except Exception:
            # 兜底：忽略不存在/已删除等情况
            pass

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_drop_hotfix_4f52f6_idx, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='wowwagomonitorstate',
                    name='wow_wago_mo_hotfix_4f52f6_idx',
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='wowdailyreport',
            new_name='wow_daily_r_report__aa83a8_idx',
            old_name='wow_daily__report__0f1e69_idx',
        ),
        migrations.RenameIndex(
            model_name='wowdailyreport',
            new_name='wow_daily_r_updated_4ad1fc_idx',
            old_name='wow_daily__updated_8dfc8c_idx',
        ),
        migrations.RenameIndex(
            model_name='wowwagomonitorstate',
            new_name='wow_wago_mo_hotfix__6f6a60_idx',
            old_name='wow_wago_mo_hotfix_b7502c_idx',
        ),
        migrations.RenameIndex(
            model_name='wowwagomonitorstate',
            new_name='wow_wago_mo_hotfix__f489ff_idx',
            old_name='wow_wago_mo_hotfix_1118a0_idx',
        ),
        migrations.RenameIndex(
            model_name='wowwagomonitorstate',
            new_name='wow_wago_mo_hotfix__e9b108_idx',
            old_name='wow_wago_mo_hotfix_4b8b02_idx',
        ),
        migrations.RenameIndex(
            model_name='wowwagomonitorstate',
            new_name='wow_wago_mo_hotfix__10480c_idx',
            old_name='wow_wago_mo_hotfix_9a1c2b_idx',
        ),
        migrations.AddField(
            model_name='portalmplusseasoncutoff',
            name='cutoff_0_1_prev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalmplusseasoncutoff',
            name='cutoff_1_prev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalmplusseasoncutoff',
            name='prev_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='content_cn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='title_cn',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
