# Generated by Django 5.1.15 on 2026-06-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0075_portalmplusseasoncutoff_prev_fields_wowarticle_translation_fields'),
        ('botend', '0075_remove_wowwagomonitorstate_wow_wago_mo_hotfix_4f52f6_idx_and_more'),
    ]

    operations = [
    ]
