# Generated by Django 5.2.13 on 2026-06-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0075_remove_wowwagomonitorstate_wow_wago_mo_hotfix_4f52f6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmplusseasoncutoff',
            name='prev_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
