# Generated by Django 5.1.15 on 2026-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0076_merge_20260607_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowHotfixReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(default='wow', max_length=32)),
                ('locale', models.CharField(default='enUS', max_length=8)),
                ('build_num', models.CharField(blank=True, default='', max_length=32)),
                ('build_str', models.CharField(blank=True, default='', max_length=64)),
                ('from_push', models.BigIntegerField(default=0)),
                ('to_push', models.BigIntegerField(default=0)),
                ('summary_title', models.CharField(blank=True, default='', max_length=255)),
                ('content_md', models.TextField(blank=True, default='')),
                ('content_html_path', models.CharField(blank=True, default='', max_length=500)),
                ('report_url', models.CharField(blank=True, default='', max_length=500)),
                ('wago_url', models.CharField(blank=True, default='', max_length=500)),
                ('changed_tables_json', models.TextField(blank=True, default='')),
                ('table_count', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_hotfix_report',
                'indexes': [models.Index(fields=['branch', 'locale'], name='wow_hot__branch__8ad3c7_idx'), models.Index(fields=['to_push'], name='wow_hot__to_pus_9a4f12_idx'), models.Index(fields=['created_at'], name='wow_hot__created_7c3a19_idx')],
                'unique_together': {('branch', 'locale', 'to_push')},
            },
        ),
    ]
