# Generated by Django 5.2.13 on 2026-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0076_portalmplusseasoncutoff_prev_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='content_cn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='title_cn',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
