# Generated by Django 6.0.6 on 2026-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0066_merge_20260521_1039'),
        ('botend', '0077_wowhotfixreport'),
    ]

    operations = [
    ]
