# Generated by Django 4.2 on 2026-06-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0080_monitortask_last_scan_time_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerspectopplayer',
            options={'verbose_name': '专精人物榜', 'verbose_name_plural': '专精人物榜'},
        ),
        migrations.AlterModelOptions(
            name='seasonmeta',
            options={'verbose_name': '赛季元数据', 'verbose_name_plural': '赛季元数据'},
        ),
        migrations.AlterModelOptions(
            name='specdungeonranking',
            options={'verbose_name': 'M+副本排名', 'verbose_name_plural': 'M+副本排名'},
        ),
        migrations.AlterModelOptions(
            name='specraidranking',
            options={'verbose_name': '团本排名', 'verbose_name_plural': '团本排名'},
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='achievement_points',
            field=models.IntegerField(blank=True, help_text='成就点数', null=True, verbose_name='成就点数'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='头像 URL', max_length=500, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='character_name',
            field=models.CharField(help_text='角色名', max_length=50, verbose_name='角色名'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='class_name',
            field=models.CharField(help_text='职业名，如 DeathKnight', max_length=30, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='faction',
            field=models.CharField(blank=True, help_text='阵营', max_length=10, null=True, verbose_name='阵营'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='gear_json',
            field=models.JSONField(blank=True, default=list, help_text='装备列表', verbose_name='装备'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='gender',
            field=models.CharField(blank=True, help_text='性别', max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='guild_name',
            field=models.CharField(blank=True, help_text='公会名', max_length=100, null=True, verbose_name='公会'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='item_level',
            field=models.FloatField(blank=True, help_text='装等', null=True, verbose_name='装等'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='数据更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='profile_url',
            field=models.CharField(blank=True, help_text='Raider.IO 主页 URL', max_length=500, null=True, verbose_name='角色主页'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='race',
            field=models.CharField(blank=True, help_text='种族', max_length=30, null=True, verbose_name='种族'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='rank',
            field=models.IntegerField(blank=True, help_text='排名', null=True, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='realm',
            field=models.CharField(help_text='服务器', max_length=50, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='realm_rank',
            field=models.IntegerField(blank=True, help_text='服务器排名', null=True, verbose_name='服内排名'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='region',
            field=models.CharField(help_text='区域 us/eu/kr/tw', max_length=10, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='score',
            field=models.FloatField(blank=True, help_text='M+ 分数', null=True, verbose_name='M+分数'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='season_id',
            field=models.IntegerField(help_text='赛季 ID', verbose_name='赛季ID'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='spec_name',
            field=models.CharField(help_text='专精名，如 Frost', max_length=30, verbose_name='专精'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='stats_crawl_status',
            field=models.IntegerField(default=0, help_text='0=待采集 1=已采集 -1=失败', verbose_name='采集状态'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='stats_json',
            field=models.JSONField(blank=True, default=dict, help_text='属性面板', verbose_name='属性面板'),
        ),
        migrations.AlterField(
            model_name='playerspectopplayer',
            name='talents_json',
            field=models.JSONField(blank=True, default=list, help_text='天赋数据', verbose_name='天赋'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否当前赛季', verbose_name='是否当前赛季'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='mplus_encounters',
            field=models.JSONField(blank=True, default=list, help_text='M+ 副本列表 [{id, name, short}, ...]', verbose_name='M+副本列表'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='mplus_zone_id',
            field=models.IntegerField(help_text='M+ 区域 ID', verbose_name='M+区域ID'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='mplus_zone_name',
            field=models.CharField(blank=True, help_text='M+ 区域名称', max_length=100, null=True, verbose_name='M+区域名称'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='raid_encounters',
            field=models.JSONField(blank=True, default=list, help_text='团本 Boss 列表 [{id, name, index}, ...]', verbose_name='团本Boss列表'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='raid_zone_id',
            field=models.IntegerField(help_text='团本区域 ID', verbose_name='团本区域ID'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='raid_zone_name',
            field=models.CharField(blank=True, help_text='团本区域名称', max_length=100, null=True, verbose_name='团本区域名称'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='rio_season',
            field=models.CharField(blank=True, help_text='Raider.IO 赛季标识，如 season-tww-3', max_length=30, null=True, verbose_name='Raider.IO赛季'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='season_key',
            field=models.CharField(help_text='赛季标识，如 tww-s3', max_length=30, unique=True, verbose_name='赛季标识'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='season_name',
            field=models.CharField(help_text='赛季名称', max_length=100, verbose_name='赛季名称'),
        ),
        migrations.AlterField(
            model_name='seasonmeta',
            name='wcl_partition',
            field=models.IntegerField(default=3, help_text='WCL 分区号', verbose_name='WCL分区号'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='affixes',
            field=models.JSONField(blank=True, default=list, help_text='词缀列表', verbose_name='词缀'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='character_name',
            field=models.CharField(help_text='角色名', max_length=50, verbose_name='角色名'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='class_name',
            field=models.CharField(help_text='职业名', max_length=30, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='clear_time',
            field=models.IntegerField(blank=True, help_text='通关时间(ms)', null=True, verbose_name='通关时间(ms)'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='dps',
            field=models.FloatField(help_text='原始 DPS', verbose_name='DPS'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='dungeon_id',
            field=models.IntegerField(help_text='WCL encounter ID', verbose_name='副本ID'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='dungeon_name',
            field=models.CharField(help_text='副本名称', max_length=100, verbose_name='副本名称'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='faction',
            field=models.IntegerField(blank=True, help_text='0=联盟 1=部落', null=True, verbose_name='阵营'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='fight_id',
            field=models.IntegerField(blank=True, help_text='WCL fight ID', null=True, verbose_name='FightID'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='gear_json',
            field=models.JSONField(blank=True, default=list, help_text='装备数据', verbose_name='装备'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='guild_name',
            field=models.CharField(blank=True, help_text='公会名', max_length=100, null=True, verbose_name='公会'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='keystone_level',
            field=models.IntegerField(blank=True, help_text='钥石等级', null=True, verbose_name='钥石等级'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='数据更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='medal',
            field=models.CharField(blank=True, help_text='gold/silver/bronze', max_length=20, null=True, verbose_name='奖牌'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='realm',
            field=models.CharField(blank=True, help_text='服务器', max_length=50, null=True, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='region',
            field=models.CharField(blank=True, help_text='区域', max_length=10, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='report_code',
            field=models.CharField(blank=True, help_text='WCL report code', max_length=50, null=True, verbose_name='WCL报告码'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='score',
            field=models.FloatField(blank=True, help_text='M+ 分数', null=True, verbose_name='M+分数'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='season_id',
            field=models.IntegerField(help_text='赛季 ID', verbose_name='赛季ID'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='spec_name',
            field=models.CharField(help_text='专精名', max_length=30, verbose_name='专精'),
        ),
        migrations.AlterField(
            model_name='specdungeonranking',
            name='talents_json',
            field=models.JSONField(blank=True, default=list, help_text='天赋数据', verbose_name='天赋'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='boss_id',
            field=models.IntegerField(help_text='WCL encounter ID', verbose_name='BossID'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='boss_name',
            field=models.CharField(help_text='Boss 名称', max_length=100, verbose_name='Boss名称'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='character_name',
            field=models.CharField(help_text='角色名', max_length=50, verbose_name='角色名'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='class_name',
            field=models.CharField(help_text='职业名', max_length=30, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='dps',
            field=models.FloatField(help_text='原始 DPS', verbose_name='DPS'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='faction',
            field=models.IntegerField(blank=True, help_text='0=联盟 1=部落', null=True, verbose_name='阵营'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='fight_id',
            field=models.IntegerField(blank=True, help_text='WCL fight ID', null=True, verbose_name='FightID'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='gear_json',
            field=models.JSONField(blank=True, default=list, help_text='装备数据', verbose_name='装备'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='guild_name',
            field=models.CharField(blank=True, help_text='公会名', max_length=100, null=True, verbose_name='公会'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='kill_time',
            field=models.IntegerField(blank=True, help_text='击杀时间(ms)', null=True, verbose_name='击杀时间(ms)'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='数据更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='realm',
            field=models.CharField(blank=True, help_text='服务器', max_length=50, null=True, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='region',
            field=models.CharField(blank=True, help_text='区域', max_length=10, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='report_code',
            field=models.CharField(blank=True, help_text='WCL report code', max_length=50, null=True, verbose_name='WCL报告码'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='season_id',
            field=models.IntegerField(help_text='赛季 ID（SeasonMeta.id）', verbose_name='赛季ID'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='spec_name',
            field=models.CharField(help_text='专精名', max_length=30, verbose_name='专精'),
        ),
        migrations.AlterField(
            model_name='specraidranking',
            name='talents_json',
            field=models.JSONField(blank=True, default=list, help_text='天赋数据', verbose_name='天赋'),
        ),
    ]
