# Generated by TRAE on 2026-06-13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0081_add_multi_raid_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowTalentNodeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, default='', max_length=30)),
                ('spec_name', models.CharField(blank=True, default='', max_length=30)),
                ('tree_type', models.CharField(blank=True, default='spec', max_length=16)),
                ('node_id', models.BigIntegerField(blank=True, null=True)),
                ('spell_id', models.BigIntegerField(blank=True, null=True)),
                ('talent_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('name_zh', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=255)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('max_points', models.IntegerField(default=1)),
                ('parents_json', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='derived', max_length=32)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'WoW天赋节点元数据',
                'verbose_name_plural': 'WoW天赋节点元数据',
                'db_table': 'wow_talent_node_metadata',
                'app_label': 'botend',
                'unique_together': {('class_name', 'spec_name', 'tree_type', 'node_id', 'spell_id')},
            },
        ),
        migrations.AddIndex(
            model_name='wowtalentnodemetadata',
            index=models.Index(fields=['class_name', 'spec_name', 'tree_type'], name='idx_talent_meta_spec'),
        ),
        migrations.AddIndex(
            model_name='wowtalentnodemetadata',
            index=models.Index(fields=['spell_id'], name='idx_talent_meta_spell'),
        ),
        migrations.AddIndex(
            model_name='wowtalentnodemetadata',
            index=models.Index(fields=['talent_id'], name='idx_talent_meta_talent'),
        ),
    ]
