# Generated by TRAE on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0082_wowtalentnodemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowtalentnodemetadata',
            name='display_spell_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
