# Generated by Django 5.2.15 on 2026-06-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0084_add_talent_build_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowtalentnodemetadata',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wowtalentnodemetadata',
            name='description_zh',
            field=models.TextField(blank=True, default=''),
        ),
    ]
