# Generated by Django 5.2.15 on 2026-06-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0090_delete_monitortasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalevent',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='portalevent',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='portalevent',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalevent',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portalevent',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='portalevent',
            index=models.Index(fields=['source', 'is_active'], name='wow_portal__source_23a759_idx'),
        ),
        migrations.AddIndex(
            model_name='portalevent',
            index=models.Index(fields=['start_at'], name='wow_portal__start_a_6261c9_idx'),
        ),
        migrations.AddIndex(
            model_name='portalevent',
            index=models.Index(fields=['last_seen_at'], name='wow_portal__last_se_9f9334_idx'),
        ),
    ]
