# Generated by Django 5.2.15 on 2026-06-29 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0091_portal_event_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowWagoBuildEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(default='wow', max_length=32)),
                ('locale', models.CharField(default='enUS', max_length=8)),
                ('from_build', models.CharField(max_length=64)),
                ('to_build', models.CharField(max_length=64)),
                ('status', models.CharField(default='detected', max_length=64)),
                ('wago_diff_url', models.CharField(blank=True, default='', max_length=500)),
                ('spell_count', models.IntegerField(default=0)),
                ('class_count', models.IntegerField(default=0)),
                ('changed_tables_json', models.TextField(blank=True, default='')),
                ('summary_title', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ext', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botend.wowskilldiffreport')),
            ],
            options={
                'db_table': 'wow_wago_build_event',
                'indexes': [
                    models.Index(fields=['branch', 'locale'], name='wow_wago_bu_branch_34d2ea_idx'),
                    models.Index(fields=['to_build'], name='wow_wago_bu_to_buil_fccfcc_idx'),
                    models.Index(fields=['status'], name='wow_wago_bu_status_76224e_idx'),
                    models.Index(fields=['detected_at'], name='wow_wago_bu_detecte_7ea7e4_idx'),
                    models.Index(fields=['updated_at'], name='wow_wago_bu_updated_635779_idx'),
                ],
                'unique_together': {('branch', 'locale', 'from_build', 'to_build')},
            },
        ),
        migrations.CreateModel(
            name='WowWagoHotfixEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(default='wow', max_length=32)),
                ('locale', models.CharField(default='enUS', max_length=8)),
                ('from_push', models.BigIntegerField(default=0)),
                ('to_push', models.BigIntegerField(default=0)),
                ('push_id', models.BigIntegerField(default=0)),
                ('build_num', models.CharField(blank=True, default='', max_length=32)),
                ('build_str', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='detected', max_length=64)),
                ('wago_url', models.CharField(blank=True, default='', max_length=500)),
                ('table_count', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
                ('changed_tables_json', models.TextField(blank=True, default='')),
                ('summary_title', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ext', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botend.wowhotfixreport')),
            ],
            options={
                'db_table': 'wow_wago_hotfix_event',
                'indexes': [
                    models.Index(fields=['branch', 'locale'], name='wow_wago_ho_branch_28e564_idx'),
                    models.Index(fields=['to_push'], name='wow_wago_ho_to_push_96147d_idx'),
                    models.Index(fields=['push_id'], name='wow_wago_ho_push_id_b53d33_idx'),
                    models.Index(fields=['status'], name='wow_wago_ho_status_a25fb6_idx'),
                    models.Index(fields=['detected_at'], name='wow_wago_ho_detecte_414ffb_idx'),
                    models.Index(fields=['updated_at'], name='wow_wago_ho_updated_c59687_idx'),
                ],
                'unique_together': {('branch', 'locale', 'to_push')},
            },
        ),
    ]
