# Generated by Django 5.2.15 on 2026-07-04 17:34

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


DEFAULT_RETAIL_TALENT_VERSION_KEY = 'retail-12.0.7'
DEFAULT_PTR_TALENT_VERSION_KEY = 'ptr-12.1.0'


def create_default_talent_version(apps, schema_editor):
    WowTalentVersion = apps.get_model('botend', 'WowTalentVersion')
    WowTalentNodeMetadata = apps.get_model('botend', 'WowTalentNodeMetadata')
    version, _ = WowTalentVersion.objects.get_or_create(
        key=DEFAULT_RETAIL_TALENT_VERSION_KEY,
        defaults={
            'label': '正式服 12.0.7',
            'branch': 'retail',
            'major_version': '12.0.7',
            'current_build': '',
            'is_active': True,
            'is_default_simulator': True,
            'is_default_player_tree': True,
            'is_default_stats': True,
            'status': 'active',
            'source_dir': '',
            'notes': '',
            'activated_at': timezone.now(),
        },
    )
    WowTalentNodeMetadata.objects.filter(talent_version__isnull=True).update(talent_version=version)
    WowTalentVersion.objects.get_or_create(
        key=DEFAULT_PTR_TALENT_VERSION_KEY,
        defaults={
            'label': 'PTR 12.1.0',
            'branch': 'ptr',
            'major_version': '12.1.0',
            'current_build': '',
            'is_active': True,
            'is_default_simulator': False,
            'is_default_player_tree': False,
            'is_default_stats': False,
            'status': 'testing',
            'source_dir': '',
            'notes': 'PTR 天赋模拟器元数据版本，默认不影响玩家详情和统计页。',
            'activated_at': timezone.now(),
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0092_wago_event_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowTalentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('branch', models.CharField(blank=True, default='retail', max_length=16)),
                ('major_version', models.CharField(blank=True, default='', max_length=32)),
                ('current_build', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default_simulator', models.BooleanField(default=False)),
                ('is_default_player_tree', models.BooleanField(default=False)),
                ('is_default_stats', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='draft', max_length=24)),
                ('source_dir', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wow_talent_version',
            },
        ),
        migrations.AddIndex(
            model_name='wowtalentversion',
            index=models.Index(fields=['branch', 'major_version'], name='idx_talent_ver_branch_major'),
        ),
        migrations.AddIndex(
            model_name='wowtalentversion',
            index=models.Index(fields=['is_active'], name='idx_talent_ver_active'),
        ),
        migrations.RemoveIndex(
            model_name='wowtalentnodemetadata',
            name='idx_talent_meta_spec',
        ),
        migrations.RemoveIndex(
            model_name='wowtalentnodemetadata',
            name='idx_talent_meta_talent',
        ),
        migrations.AlterUniqueTogether(
            name='wowtalentnodemetadata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wowtalentnodemetadata',
            name='talent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='botend.wowtalentversion'),
        ),
        migrations.RunPython(create_default_talent_version, noop_reverse),
        migrations.AlterUniqueTogether(
            name='wowtalentnodemetadata',
            unique_together={('talent_version', 'class_name', 'spec_name', 'tree_type', 'node_id', 'spell_id')},
        ),
        migrations.AddIndex(
            model_name='wowtalentnodemetadata',
            index=models.Index(fields=['talent_version', 'class_name', 'spec_name', 'tree_type'], name='idx_talent_meta_ver_spec'),
        ),
        migrations.AddIndex(
            model_name='wowtalentnodemetadata',
            index=models.Index(fields=['talent_version', 'talent_id'], name='idx_talent_meta_ver_talent'),
        ),
    ]
