# Generated by Django 5.2.15 on 2026-07-05 04:23

from django.db import migrations
from django.utils import timezone

from botend.wow.talents.default_versions import DEFAULT_TALENT_VERSIONS


def ensure_versions(apps, schema_editor):
    WowTalentVersion = apps.get_model('botend', 'WowTalentVersion')
    now = timezone.now()
    for item in DEFAULT_TALENT_VERSIONS:
        payload = dict(item)
        key = payload.pop('key')
        defaults = dict(payload)
        defaults['activated_at'] = now if payload.get('is_active') else None
        obj, created = WowTalentVersion.objects.get_or_create(key=key, defaults=defaults)
        if created:
            continue
        update_fields = []
        for field, value in defaults.items():
            if field in ('source_dir', 'notes', 'current_build') and getattr(obj, field, ''):
                continue
            if getattr(obj, field) != value:
                setattr(obj, field, value)
                update_fields.append(field)
        if update_fields:
            obj.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0093_talent_metadata_versioning'),
    ]

    operations = [
        migrations.RunPython(ensure_versions, noop_reverse),
    ]
