# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0094_ensure_talent_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowtalentnodemetadata',
            name='flags',
            field=models.IntegerField(default=0, help_text='DB2 TraitNode.Flags；Flags=8 表示赠送天赋（默认授予，无法取消）'),
        ),
    ]
