# Generated by Django 5.2.15 on 2026-07-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0096_simc_default_apl_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simctask',
            name='ext',
            field=models.TextField(blank=True, help_text='扩展信息', null=True),
        ),
    ]
