# Generated by Django 5.2.15 on 2026-07-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0097_simc_task_ext_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='auto_update',
            field=models.BooleanField(default=True, help_text='是否自动拉取并编译更新'),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='is_updating',
            field=models.BooleanField(default=False, help_text='是否正在本地编译更新'),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, help_text='上次检查时间', null=True),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='last_error',
            field=models.CharField(blank=True, default='', help_text='最近更新错误', max_length=500),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='latest_version',
            field=models.CharField(blank=True, default='', help_text='检测到的源码上游版本/提交', max_length=128),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='platform',
            field=models.CharField(default='linux64', help_text='平台标识，如 linux64/linuxarm64', max_length=32),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='simc_path',
            field=models.CharField(default='', help_text='SimC本地编译产物路径', max_length=500),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='update_progress',
            field=models.IntegerField(default=0, help_text='更新进度百分比 0-100'),
        ),
        migrations.AlterField(
            model_name='simcbackendbinary',
            name='update_status',
            field=models.CharField(blank=True, default='', help_text='更新状态提示', max_length=255),
        ),
    ]
