# Generated by Django 5.2.15 on 2026-07-09

from django.db import migrations, models


def migrate_simc_content(apps, schema_editor):
    SimcContentTemplate = apps.get_model('botend', 'SimcContentTemplate')
    SimcTemplate = apps.get_model('botend', 'SimcTemplate')
    SimcDefaultApl = apps.get_model('botend', 'SimcDefaultApl')

    for old in SimcTemplate.objects.all().iterator():
        SimcContentTemplate.objects.update_or_create(
            template_type='base_template',
            source='simc_upstream',
            spec=old.spec or 'default',
            name=f'基础模板 {old.spec or "default"}',
            defaults={
                'class_name': '',
                'content': old.template_content or '',
                'is_active': old.is_active,
                'is_selectable': False,
            },
        )

    for old in SimcDefaultApl.objects.all().iterator():
        SimcContentTemplate.objects.update_or_create(
            template_type='default_apl',
            source='simc_upstream',
            spec=old.spec or 'default',
            name=f'默认APL {old.spec or "default"}',
            defaults={
                'class_name': old.class_name or '',
                'content': old.apl_content or '',
                'is_active': old.is_active,
                'is_selectable': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0098_alter_simcbackendbinary_auto_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcContentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='展示名称', max_length=200)),
                ('template_type', models.CharField(choices=[('base_template', '基础模板'), ('default_apl', '默认APL'), ('custom_apl', '个人APL')], default='base_template', help_text='内容类型', max_length=32)),
                ('source', models.CharField(choices=[('simc_upstream', 'SimC源码同步'), ('user', '用户维护')], default='user', help_text='内容来源', max_length=32)),
                ('spec', models.CharField(default='default', help_text='专精标识，如 warrior_fury/default', max_length=100)),
                ('class_name', models.CharField(blank=True, default='', help_text='职业英文名，如 warrior', max_length=50)),
                ('content', models.TextField(help_text='模板/APL内容')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('is_selectable', models.BooleanField(default=True, help_text='任务发起时是否可选择')),
                ('sync_version', models.CharField(blank=True, default='', help_text='同步来源版本/提交', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SimC模板/APL',
                'verbose_name_plural': 'SimC模板/APL',
                'db_table': 'simc_content_template',
                'indexes': [
                    models.Index(fields=['template_type', 'spec', 'is_active'], name='simc_conten_templat_b126da_idx'),
                    models.Index(fields=['source', 'template_type'], name='simc_conten_source_1d0861_idx'),
                ],
            },
        ),
        migrations.RunPython(migrate_simc_content, migrations.RunPython.noop),
        migrations.DeleteModel(name='SimcTemplate'),
        migrations.DeleteModel(name='SimcDefaultApl'),
    ]
