# Generated by Django 5.2.15 on 2026-07-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0099_simc_content_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simcprofile',
            name='action_list',
        ),
        migrations.RemoveField(
            model_name='simcprofile',
            name='fight_style',
        ),
        migrations.RemoveField(
            model_name='simcprofile',
            name='target_count',
        ),
        migrations.RemoveField(
            model_name='simcprofile',
            name='time',
        ),
    ]
