# Generated by Django 5.2.15 on 2026-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0101_refactor_simc_secondary_stat_rule_by_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcprofile',
            name='battlenet_character',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='battlenet_realm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='battlenet_region',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='player_config_mode',
            field=models.CharField(default='battlenet', help_text='玩家配置来源：battlenet/manual_equipment', max_length=50),
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='player_equipment',
            field=models.TextField(blank=True, default='', help_text='手动装备/天赋玩家块'),
        ),
    ]
