# Generated by Django 5.2.15 on 2026-07-14 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0105_remove_unsupported_default_player_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='simctask',
            name='candidate_label',
            field=models.CharField(blank=True, default='', help_text='对比任务标签，如 crit+1000', max_length=200),
        ),
        migrations.AddField(
            model_name='simctask',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='完成时间', null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='error_detail',
            field=models.TextField(blank=True, help_text='创建或执行错误详情', null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='final_simc_content',
            field=models.TextField(blank=True, help_text='冻结的完整SimC输入正文，Worker直接执行', null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='fragment_manifest',
            field=models.TextField(blank=True, help_text='JSON manifest v2: 记录各槽位来源和版本', null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='input_hash',
            field=models.CharField(blank=True, default='', help_text='final_simc_content的SHA256，用于去重', max_length=64),
        ),
        migrations.AddField(
            model_name='simctask',
            name='result_summary',
            field=models.TextField(blank=True, help_text='结果摘要JSON：DPS/HPS等关键指标', null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='开始执行时间', null=True),
        ),
        migrations.AlterField(
            model_name='simctask',
            name='current_status',
            field=models.IntegerField(default=0, help_text='当前状态：0=待执行,1=执行中,2=完成,3=失败'),
        ),
        migrations.AlterField(
            model_name='simctask',
            name='ext',
            field=models.TextField(blank=True, help_text='扩展信息（legacy兼容）', null=True),
        ),
        migrations.CreateModel(
            name='SimcTaskArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(help_text='产物类型：html_report/json_stats/log', max_length=50)),
                ('file_path', models.CharField(help_text='相对static/的文件路径', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小（字节）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='botend.simctask')),
            ],
            options={
                'verbose_name': 'SimC任务产物',
                'verbose_name_plural': 'SimC任务产物',
                'db_table': 'simc_task_artifact',
            },
        ),
        migrations.CreateModel(
            name='SimcTaskBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='用户ID')),
                ('name', models.CharField(help_text='批次名称', max_length=200)),
                ('batch_type', models.CharField(default='comparison', help_text='批次类型：comparison/attribute_sweep', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SimC任务批次',
                'verbose_name_plural': 'SimC任务批次',
                'db_table': 'simc_task_batch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='simc_task_b_user_id_717b38_idx')],
            },
        ),
        migrations.AddField(
            model_name='simctask',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='所属批次', null=True, on_delete=django.db.models.deletion.SET_NULL, to='botend.simctaskbatch'),
        ),
        migrations.AddIndex(
            model_name='simctask',
            index=models.Index(fields=['user_id', '-create_time'], name='simc_task_user_id_d83ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='simctask',
            index=models.Index(fields=['batch', '-create_time'], name='simc_task_batch_i_58f508_idx'),
        ),
        migrations.AddIndex(
            model_name='simctask',
            index=models.Index(fields=['input_hash'], name='simc_task_input_h_a08718_idx'),
        ),
        migrations.AddIndex(
            model_name='simctaskartifact',
            index=models.Index(fields=['task', 'artifact_type'], name='simc_task_a_task_id_c50497_idx'),
        ),
    ]
