# Generated by Django 5.2.15 on 2026-07-16 12:43

import django.db.models.deletion
from django.db import migrations, models


def clear_legacy_simc_tasks(apps, schema_editor):
    """
    清理所有旧的 SimcTask 数据及其关联记录。

    用户明确要求：不兼容旧版本，旧版本直接清理。
    此迁移后只接受完整引用型任务，旧的冻结正文任务不再支持。
    """
    SimcTask = apps.get_model('botend', 'SimcTask')
    SimcTaskBatch = apps.get_model('botend', 'SimcTaskBatch')
    SimcTaskArtifact = apps.get_model('botend', 'SimcTaskArtifact')

    # 先删除依赖 Task 的 Artifact（FK ON DELETE CASCADE 已处理，但显式清理更安全）
    artifact_count = SimcTaskArtifact.objects.count()
    if artifact_count > 0:
        SimcTaskArtifact.objects.all().delete()
        print(f"  已清理 {artifact_count} 条 SimcTaskArtifact 记录")

    # 删除所有 Task（包括有 batch 的和无 batch 的）
    task_count = SimcTask.objects.count()
    if task_count > 0:
        SimcTask.objects.all().delete()
        print(f"  已清理 {task_count} 条 SimcTask 记录")

    # 删除所有 Batch
    batch_count = SimcTaskBatch.objects.count()
    if batch_count > 0:
        SimcTaskBatch.objects.all().delete()
        print(f"  已清理 {batch_count} 条 SimcTaskBatch 记录")

    print("  旧 SimC 任务数据清理完成。后续只接受引用型任务。")


def reverse_clear(apps, schema_editor):
    """回滚时无需恢复已删除数据（用户已明确不兼容旧版本）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0109_create_simc_apl_and_migrate_data'),
    ]

    operations = [
        # Step 1: 清理所有旧任务数据
        migrations.RunPython(clear_legacy_simc_tasks, reverse_clear),

        # Step 2: Create SimcResourceVersion table
        migrations.CreateModel(
            name='SimcResourceVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(help_text='资源类型: profile/template/apl', max_length=20)),
                ('resource_id', models.BigIntegerField(help_text='资源ID（对应 SimcProfile.id/SimcContentTemplate.id/SimcApl.id）')),
                ('content_hash', models.CharField(help_text='内容SHA256，用于版本去重', max_length=64)),
                ('payload', models.JSONField(help_text='冻结的资源内容和元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': 'SimC资源版本',
                'verbose_name_plural': 'SimC资源版本',
                'db_table': 'simc_resource_version',
                'indexes': [
                    models.Index(fields=['resource_type', 'resource_id', '-created_at'], name='simc_resour_resourc_20f4a6_idx'),
                    models.Index(fields=['content_hash'], name='simc_resour_content_42c1d3_idx'),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name='simcresourceversion',
            unique_together={('resource_type', 'resource_id', 'content_hash')},
        ),

        # Step 3: Add new reference fields to SimcTask
        migrations.AddField(
            model_name='simctask',
            name='apl',
            field=models.ForeignKey(blank=True, help_text='引用的APL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='botend.simcapl'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='mode',
            field=models.CharField(blank=True, default='normal', help_text='任务模式：normal/comparison/attribute_sweep', max_length=50),
        ),
        migrations.AddField(
            model_name='simctask',
            name='mode_params',
            field=models.JSONField(blank=True, help_text='模式参数：对比项、寻优范围等', null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='引用的玩家配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='botend.simcprofile'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='profile_version',
            field=models.ForeignKey(blank=True, help_text='Profile版本快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_tasks', to='botend.simcresourceversion'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='template_version',
            field=models.ForeignKey(blank=True, help_text='Template版本快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_tasks', to='botend.simcresourceversion'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='apl_version',
            field=models.ForeignKey(blank=True, help_text='APL版本快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apl_tasks', to='botend.simcresourceversion'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='simulation_params',
            field=models.JSONField(blank=True, help_text='模拟参数：iterations, fight_style等', null=True),
        ),
        migrations.AddField(
            model_name='simctask',
            name='source_task',
            field=models.ForeignKey(blank=True, help_text='重跑来源任务', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='botend.simctask'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='template',
            field=models.ForeignKey(blank=True, help_text='引用的基础模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='botend.simccontenttemplate'),
        ),

        # Step 4: Remove legacy frozen fields and their index
        migrations.RemoveIndex(
            model_name='simctask',
            name='simc_task_input_h_a08718_idx',
        ),
        migrations.RemoveField(
            model_name='simctask',
            name='final_simc_content',
        ),
        migrations.RemoveField(
            model_name='simctask',
            name='fragment_manifest',
        ),
        migrations.RemoveField(
            model_name='simctask',
            name='input_hash',
        ),

        # Step 5: Create SimulationRun table
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1, help_text='执行序号（轮次/候选编号）')),
                ('candidate_label', models.CharField(blank=True, default='', help_text='候选标签，如 baseline/crit+1000/apl_variant_2', max_length=200)),
                ('status', models.CharField(default='pending', help_text='状态：pending/running/completed/failed', max_length=20)),
                ('input_hash', models.CharField(blank=True, default='', help_text='本次输入的SHA256', max_length=64)),
                ('resource_manifest', models.JSONField(blank=True, help_text='本次执行时解析的资源版本元数据', null=True)),
                ('result_summary', models.JSONField(blank=True, help_text='结果摘要：DPS/HPS等关键指标', null=True)),
                ('error_detail', models.TextField(blank=True, help_text='执行错误详情', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='开始时间', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('task', models.ForeignKey(help_text='所属任务', on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='botend.simctask')),
            ],
            options={
                'verbose_name': 'SimC执行记录',
                'verbose_name_plural': 'SimC执行记录',
                'db_table': 'simc_simulation_run',
                'ordering': ['task', 'sequence'],
                'indexes': [
                    models.Index(fields=['task', 'sequence'], name='simc_simula_task_id_d5a6d5_idx'),
                    models.Index(fields=['status'], name='simc_simula_status_24ae83_idx'),
                    models.Index(fields=['input_hash'], name='simc_simula_input_h_09b5a5_idx'),
                ],
            },
        ),
    ]
