# Generated by Django 5.2 on 2026-07-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('botend', '0112_replace_nga_domain')]

    operations = [
        migrations.AddField(
            model_name='simctaskartifact',
            name='run',
            field=models.ForeignKey(
                blank=True, help_text='生成该产物的具体执行轮次', null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='artifacts', to='botend.simulationrun',
            ),
        ),
    ]
