# Generated by Django 5.2 on 2026-07-17

from django.db import migrations


def enable_upstream_base_templates(apps, schema_editor):
    SimcContentTemplate = apps.get_model('botend', 'SimcContentTemplate')
    SimcContentTemplate.objects.filter(
        template_type='base_template',
        source='simc_upstream',
        is_active=True,
    ).update(is_selectable=True)


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0113_simctaskartifact_run'),
    ]

    operations = [
        migrations.RunPython(enable_upstream_base_templates, migrations.RunPython.noop),
    ]
