# Generated by Django 5.2.15 on 2026-07-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0116_normalize_fury_hero_tree_dispatch'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerspectopplayer',
            index=models.Index(fields=['season_id', 'class_name', '-score', 'rank', 'id'], name='idx_season_class_top'),
        ),
    ]
