# Generated by Django 5.2.15 on 2026-07-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0117_add_top_player_class_score_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcAplSymbol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('simc_revision', models.CharField(max_length=128)),
                ('wow_build', models.CharField(max_length=64)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spec', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_tree', models.CharField(blank=True, max_length=100, null=True)),
                ('class_key', models.CharField(default='', editable=False, max_length=50)),
                ('spec_key', models.CharField(default='', editable=False, max_length=100)),
                ('hero_tree_key', models.CharField(default='', editable=False, max_length=100)),
                ('token', models.CharField(max_length=200)),
                ('symbol_kind', models.CharField(choices=[('action', 'Action'), ('pseudo_action', 'Pseudo action'), ('action_option', 'Action option'), ('expression', 'Expression'), ('option', 'Option'), ('namespace', 'Namespace'), ('resource', 'Resource'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('dot', 'Damage over time'), ('cooldown', 'Cooldown'), ('talent', 'Talent'), ('hero_tree', 'Hero tree')], default='action', max_length=32)),
                ('spell_id', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('simc_manifest', 'SimC manifest'), ('system_apl', 'System APL'), ('wago', 'Wago'), ('manual', 'Verified manual fact')], default='simc_manifest', max_length=32)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SimC APL symbol fact',
                'verbose_name_plural': 'SimC APL symbol facts',
                'db_table': 'simc_apl_symbol',
                'ordering': ['simc_revision', 'symbol_kind', 'token', 'id'],
                'indexes': [models.Index(fields=['simc_revision', 'spec', 'symbol_kind', 'token'], name='simc_sym_rev_spec_kind_tok_idx'), models.Index(fields=['simc_revision', 'spell_id'], name='simc_sym_rev_spell_idx'), models.Index(fields=['simc_revision', 'class_name', 'hero_tree'], name='simc_sym_rev_class_hero_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('simc_revision', 'wow_build', 'class_key', 'spec_key', 'hero_tree_key', 'token', 'symbol_kind'), name='simc_symbol_version_scope_uniq'),
                    models.CheckConstraint(condition=models.Q(models.Q(('class_key', ''), ('class_name__isnull', True)), models.Q(('class_name__isnull', False), models.Q(('class_name', ''), _negated=True), ('class_name', models.F('class_key'))), _connector='OR'), name='simc_symbol_class_scope_key_ck'),
                    models.CheckConstraint(condition=models.Q(models.Q(('spec__isnull', True), ('spec_key', '')), models.Q(('spec__isnull', False), models.Q(('spec', ''), _negated=True), ('spec', models.F('spec_key'))), _connector='OR'), name='simc_symbol_spec_scope_key_ck'),
                    models.CheckConstraint(condition=models.Q(models.Q(('hero_tree__isnull', True), ('hero_tree_key', '')), models.Q(('hero_tree__isnull', False), models.Q(('hero_tree', ''), _negated=True), ('hero_tree', models.F('hero_tree_key'))), _connector='OR'), name='simc_symbol_hero_scope_key_ck'),
                ],
            },
        ),
    ]
