# Generated by Django 5.2.13 on 2026-07-24 09:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0122_simcaplsymbol_trait_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythicPlannerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=80, unique=True)),
                ('default_dungeon_key', models.CharField(blank=True, default='', max_length=100)),
                ('default_dungeon_level', models.PositiveIntegerField(default=10)),
                ('min_dungeon_level', models.PositiveIntegerField(default=2)),
                ('max_dungeon_level', models.PositiveIntegerField(default=35)),
                ('group_selection_default', models.BooleanField(default=True)),
                ('live_sync_enabled', models.BooleanField(default=True)),
                ('allow_public_route_share', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mythic_planner_config',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonDataVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('game_version', models.CharField(blank=True, default='', max_length=40)),
                ('season', models.CharField(blank=True, default='', max_length=80)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('source_name', models.CharField(blank=True, default='', max_length=160)),
                ('source_reference', models.CharField(blank=True, default='', max_length=500)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mythic_dungeon_data_version',
                'ordering': ['-is_active', '-imported_at', 'key'],
                'indexes': [models.Index(fields=['is_active', 'imported_at'], name='md_data_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('external_index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('name_zh', models.CharField(blank=True, default='', max_length=160)),
                ('short_name', models.CharField(blank=True, default='', max_length=32)),
                ('map_id', models.IntegerField(blank=True, null=True)),
                ('total_enemy_forces', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeons', to='botend.mythicdungeondataversion')),
            ],
            options={
                'db_table': 'mythic_dungeon',
                'ordering': ['order', 'name_zh', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonEnemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('npc_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('name_zh', models.CharField(blank=True, default='', max_length=160)),
                ('enemy_forces', models.PositiveIntegerField(default=0)),
                ('base_health', models.PositiveBigIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('creature_type', models.CharField(blank=True, default='', max_length=80)),
                ('icon_url', models.CharField(blank=True, default='', max_length=1000)),
                ('marker_color', models.CharField(blank=True, default='#94a3b8', max_length=32)),
                ('is_boss', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('traits', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='botend.mythicdungeon')),
            ],
            options={
                'db_table': 'mythic_dungeon_enemy',
                'ordering': ['is_boss', 'name_zh', 'name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=160)),
                ('name_zh', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('description_zh', models.TextField(blank=True, default='')),
                ('icon_url', models.CharField(blank=True, default='', max_length=1000)),
                ('interruptible', models.BooleanField(default=False)),
                ('dispel_type', models.CharField(blank=True, default='', max_length=40)),
                ('danger_level', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='botend.mythicdungeonenemy')),
            ],
            options={
                'db_table': 'mythic_dungeon_ability',
                'ordering': ['order', '-danger_level', 'name_zh', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('floor_index', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=160)),
                ('name_zh', models.CharField(blank=True, default='', max_length=160)),
                ('background_url', models.CharField(blank=True, default='', max_length=1000)),
                ('background_color', models.CharField(blank=True, default='#66533f', max_length=32)),
                ('map_width', models.PositiveIntegerField(default=1000)),
                ('map_height', models.PositiveIntegerField(default=700)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='botend.mythicdungeon')),
            ],
            options={
                'db_table': 'mythic_dungeon_floor',
                'ordering': ['order', 'floor_index'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonPoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('poi_type', models.CharField(default='note', max_length=60)),
                ('x', models.FloatField(default=50.0)),
                ('y', models.FloatField(default=50.0)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('icon_url', models.CharField(blank=True, default='', max_length=1000)),
                ('target_floor_key', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='botend.mythicdungeonfloor')),
            ],
            options={
                'db_table': 'mythic_dungeon_poi',
                'ordering': ['poi_type', 'label', 'key'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('dungeon_level', models.PositiveIntegerField(default=10)),
                ('route_data', models.JSONField(blank=True, default=dict)),
                ('share_code', models.TextField(blank=True, default='')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='botend.mythicdungeon')),
            ],
            options={
                'db_table': 'mythic_dungeon_route',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonSpawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('x', models.FloatField(default=50.0)),
                ('y', models.FloatField(default=50.0)),
                ('group_key', models.CharField(blank=True, default='', max_length=100)),
                ('scale', models.FloatField(default=1.0)),
                ('patrol', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawns', to='botend.mythicdungeonenemy')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawns', to='botend.mythicdungeonfloor')),
            ],
            options={
                'db_table': 'mythic_dungeon_spawn',
                'ordering': ['floor__order', 'y', 'x', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='mythicdungeon',
            index=models.Index(fields=['data_version', 'is_active', 'order'], name='md_dungeon_ver_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeon',
            constraint=models.UniqueConstraint(fields=('data_version', 'key'), name='uniq_md_dungeon_version_key'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonenemy',
            index=models.Index(fields=['dungeon', 'is_active', 'name'], name='md_enemy_dungeon_name_idx'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonenemy',
            index=models.Index(fields=['npc_id'], name='md_enemy_npc_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonenemy',
            constraint=models.UniqueConstraint(fields=('dungeon', 'key'), name='uniq_md_enemy_dungeon_key'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonability',
            index=models.Index(fields=['enemy', 'is_active', 'order'], name='md_ability_enemy_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonability',
            constraint=models.UniqueConstraint(fields=('enemy', 'spell_id'), name='uniq_md_ability_enemy_spell'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonfloor',
            index=models.Index(fields=['dungeon', 'is_active', 'order'], name='md_floor_dungeon_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonfloor',
            constraint=models.UniqueConstraint(fields=('dungeon', 'key'), name='uniq_md_floor_dungeon_key'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonfloor',
            constraint=models.UniqueConstraint(fields=('dungeon', 'floor_index'), name='uniq_md_floor_dungeon_index'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonpoi',
            index=models.Index(fields=['floor', 'is_active'], name='md_poi_floor_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonpoi',
            constraint=models.UniqueConstraint(fields=('floor', 'key'), name='uniq_md_poi_floor_key'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonroute',
            index=models.Index(fields=['owner_user_id', 'is_active', 'updated_at'], name='md_route_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonroute',
            index=models.Index(fields=['share_id', 'is_public', 'is_active'], name='md_route_share_idx'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonspawn',
            index=models.Index(fields=['floor', 'is_active'], name='md_spawn_floor_idx'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonspawn',
            index=models.Index(fields=['group_key'], name='md_spawn_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonspawn',
            constraint=models.UniqueConstraint(fields=('enemy', 'key'), name='uniq_md_spawn_enemy_key'),
        ),
    ]
