# Generated by Django 5.2.13 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0123_mythicplannerconfig_mythicdungeondataversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythicDungeonSpell',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('spell_id', models.BigIntegerField()),
                ('source_branch', models.CharField(blank=True, default='', max_length=32)),
                ('source_locale', models.CharField(blank=True, default='zhCN', max_length=8)),
                ('snapshot_build', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('name_zh', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('description_zh', models.TextField(blank=True, default='')),
                ('aura_description', models.TextField(blank=True, default='')),
                ('aura_description_zh', models.TextField(blank=True, default='')),
                ('icon_file_data_id', models.BigIntegerField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, default='', max_length=255)),
                ('icon_url', models.CharField(blank=True, default='', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'data_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='spells',
                        to='botend.mythicdungeondataversion',
                    ),
                ),
            ],
            options={
                'db_table': 'mythic_dungeon_spell',
                'ordering': ['spell_id'],
                'indexes': [
                    models.Index(
                        fields=['data_version', 'is_active', 'spell_id'],
                        name='md_spell_ver_active_idx',
                    ),
                    models.Index(fields=['spell_id'], name='md_spell_id_idx'),
                    models.Index(
                        fields=['source_branch', 'snapshot_build'],
                        name='md_spell_source_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('data_version', 'spell_id'),
                        name='uniq_md_spell_version_id',
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name='mythicdungeonability',
            name='spell_record',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ability_links',
                to='botend.mythicdungeonspell',
            ),
        ),
    ]
