# Generated by Django 5.2.13 on 2026-07-27 07:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_selection_groups(apps, schema_editor):
    DataVersion = apps.get_model('botend', 'MythicDungeonDataVersion')
    Dungeon = apps.get_model('botend', 'MythicDungeon')
    SelectionGroup = apps.get_model('botend', 'MythicDungeonSelectionGroup')
    SelectionMembership = apps.get_model(
        'botend',
        'MythicDungeonSelectionMembership',
    )

    for version in DataVersion.objects.all().iterator():
        dungeons = list(Dungeon.objects.filter(data_version_id=version.id))
        dungeon_by_index = {
            dungeon.external_index: dungeon
            for dungeon in dungeons
            if dungeon.external_index is not None
        }
        memberships_by_key = {}
        for dungeon in dungeons:
            rows = (dungeon.metadata or {}).get('selection_groups', [])
            if not isinstance(rows, list):
                continue
            for row in rows:
                if not isinstance(row, dict) or not row.get('key'):
                    continue
                memberships_by_key.setdefault(str(row['key']), []).append((
                    int(row.get('dungeon_order') or 0),
                    dungeon,
                ))

        group_rows = (version.metadata or {}).get(
            'dungeon_selection_groups',
            [],
        )
        if not isinstance(group_rows, list):
            continue
        for group_index, row in enumerate(group_rows):
            if not isinstance(row, dict) or not row.get('key'):
                continue
            key = str(row['key'])
            group, _ = SelectionGroup.objects.update_or_create(
                data_version_id=version.id,
                key=key,
                defaults={
                    'name': str(row.get('name') or key),
                    'name_zh': str(
                        row.get('name_zh')
                        or row.get('name')
                        or key
                    ),
                    'order': int(row.get('order') or group_index),
                    'is_active': True,
                    'metadata': {'source': 'legacy_metadata'},
                },
            )
            members = memberships_by_key.get(key, [])
            if not members:
                indexes = row.get('dungeon_indexes', [])
                if isinstance(indexes, list):
                    members = [
                        (order, dungeon_by_index[index])
                        for order, index in enumerate(indexes, start=1)
                        if index in dungeon_by_index
                    ]
            for order, dungeon in members:
                SelectionMembership.objects.update_or_create(
                    selection_group_id=group.id,
                    dungeon_id=dungeon.id,
                    defaults={
                        'order': order,
                        'is_active': True,
                        'metadata': {'source': 'legacy_metadata'},
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0124_mythicdungeonspell_ability_spell_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythicDungeonSelectionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=160)),
                ('name_zh', models.CharField(blank=True, default='', max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_groups', to='botend.mythicdungeondataversion')),
            ],
            options={
                'db_table': 'mythic_dungeon_selection_group',
                'ordering': ['order', 'name_zh', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MythicDungeonSelectionMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_memberships', to='botend.mythicdungeon')),
                ('selection_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='botend.mythicdungeonselectiongroup')),
            ],
            options={
                'db_table': 'mythic_dungeon_selection_membership',
                'ordering': ['selection_group__order', 'order', 'dungeon__order'],
            },
        ),
        migrations.AddIndex(
            model_name='mythicdungeonselectiongroup',
            index=models.Index(fields=['data_version', 'is_active', 'order'], name='md_sel_group_ver_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonselectiongroup',
            constraint=models.UniqueConstraint(fields=('data_version', 'key'), name='uniq_md_select_group_version_key'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonselectionmembership',
            index=models.Index(fields=['selection_group', 'is_active', 'order'], name='md_sel_member_group_idx'),
        ),
        migrations.AddIndex(
            model_name='mythicdungeonselectionmembership',
            index=models.Index(fields=['dungeon', 'is_active'], name='md_sel_member_dungeon_idx'),
        ),
        migrations.AddConstraint(
            model_name='mythicdungeonselectionmembership',
            constraint=models.UniqueConstraint(fields=('selection_group', 'dungeon'), name='uniq_md_select_group_dungeon'),
        ),
        migrations.RunPython(
            backfill_selection_groups,
            migrations.RunPython.noop,
        ),
    ]
