# Generated by Django 5.2.13 on 2026-07-28 02:15

import botend.models
import django.db.models.deletion
from django.db import migrations, models


def use_innodb_for_mysql(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SET SESSION default_storage_engine=InnoDB')


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0125_mythic_dungeon_selection_groups'),
    ]

    operations = [
        migrations.RunPython(
            use_innodb_for_mysql,
            reverse_code=migrations.RunPython.noop,
            atomic=False,
        ),
        migrations.CreateModel(
            name='MythicDungeonRouteShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=botend.models.generate_mythic_route_share_token, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('dungeon_level', models.PositiveIntegerField(default=10)),
                ('route_data', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_shares', to='botend.mythicdungeon')),
            ],
            options={
                'db_table': 'mythic_dungeon_route_share',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='md_share_active_created_idx')],
            },
        ),
    ]
