# Generated by Django 5.2.15 on 2026-07-26 02:22

from django.db import migrations, models


def move_default_players_to_profiles(apps, schema_editor):
    SimcContentTemplate = apps.get_model('botend', 'SimcContentTemplate')
    SimcProfile = apps.get_model('botend', 'SimcProfile')

    default_players = SimcContentTemplate.objects.filter(
        template_type='default_player',
    ).order_by('id')
    for template in default_players.iterator():
        is_canonical_upstream = (
            template.owner_user_id is None
            and template.source == 'simc_upstream'
            and template.is_active
        )
        system_key = (
            f'simc_upstream:{template.spec}'
            if is_canonical_upstream
            else f'legacy_default_player:{template.pk}'
        )
        SimcProfile.objects.update_or_create(
            system_key=system_key,
            defaults={
                'user_id': template.owner_user_id,
                'name': template.name,
                'source': template.source,
                'class_name': template.class_name,
                'sync_version': template.sync_version,
                'spec': template.spec,
                'player_config_mode': 'manual_equipment',
                'player_equipment': template.content,
                'is_active': template.is_active,
            },
        )

    # Every default-player row has been preserved in SimcProfile; only base
    # templates remain in the structurally dedicated template table.
    SimcContentTemplate.objects.exclude(template_type='base_template').delete()


def restore_default_players_to_templates(apps, schema_editor):
    SimcContentTemplate = apps.get_model('botend', 'SimcContentTemplate')
    SimcProfile = apps.get_model('botend', 'SimcProfile')

    profiles = SimcProfile.objects.filter(system_key__startswith='simc_upstream:') | SimcProfile.objects.filter(
        system_key__startswith='legacy_default_player:'
    )
    for profile in profiles.iterator():
        owner = 'global' if profile.user_id is None else profile.user_id
        SimcContentTemplate.objects.create(
            template_type='default_player',
            owner_user_id=profile.user_id,
            spec=profile.spec,
            active_unique_key=(
                f'default_player:{owner}:{profile.spec}' if profile.is_active else None
            ),
            name=profile.name,
            source=profile.source,
            class_name=profile.class_name,
            content=profile.player_equipment,
            is_active=profile.is_active,
            is_selectable=True,
            sync_version=profile.sync_version,
        )
    profiles.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0127_prune_simc_content_templates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simccontenttemplate',
            name='simc_conten_templat_b126da_idx',
        ),
        migrations.RemoveIndex(
            model_name='simccontenttemplate',
            name='simc_conten_source_1d0861_idx',
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='class_name',
            field=models.CharField(blank=True, default='', help_text='职业英文名，如 warrior', max_length=50),
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='source',
            field=models.CharField(choices=[('user', '用户维护'), ('simc_upstream', 'SimC源码同步')], default='user', help_text='配置来源', max_length=32),
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='sync_version',
            field=models.CharField(blank=True, default='', help_text='同步来源版本/提交', max_length=128),
        ),
        migrations.AddField(
            model_name='simcprofile',
            name='system_key',
            field=models.CharField(blank=True, help_text='系统配置稳定标识', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='simcprofile',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='用户ID，NULL表示系统玩家配置', null=True),
        ),
        migrations.RunPython(move_default_players_to_profiles, restore_default_players_to_templates),
        migrations.RemoveField(
            model_name='simccontenttemplate',
            name='template_type',
        ),
        migrations.AddIndex(
            model_name='simccontenttemplate',
            index=models.Index(fields=['spec', 'is_active'], name='simc_conten_spec_d8c5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='simccontenttemplate',
            index=models.Index(fields=['source'], name='simc_conten_source_c05923_idx'),
        ),
    ]
