# Generated by Django 5.2.15 on 2026-07-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0128_split_simc_player_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcaplsymbol',
            name='identity_candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='simcaplsymbol',
            name='identity_reason',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='simcaplsymbol',
            name='identity_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
