# Generated by Django 5.2.13 on 2026-07-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0126_mythic_dungeon_route_shares'),
        ('botend', '0133_backfill_simc_benchmark_results'),
    ]

    operations = [
    ]
