# Generated by Django 5.2.13 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0134_merge_20260728_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcprofile',
            name='version',
            field=models.CharField(default='12.0', help_text='Profile 游戏版本，如 12.0', max_length=16),
        ),
    ]
