# Generated by Django 5.2.15 on 2026-07-28 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0138_simctask_execution_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcAgentEnrollmentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=32, unique=True)),
                ('secret_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_enrollment_codes', to='botend.simcbackendbinary')),
                ('consumed_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_enrollment_codes', to='botend.simcagent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_simc_agent_enrollment_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simc_agent_enrollment_code',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['backend', 'expires_at'], name='simc_agcode_back_exp_idx'), models.Index(fields=['consumed_at', 'revoked_at'], name='simc_agcode_state_idx')],
            },
        ),
    ]
