# Generated by Django 5.2.15 on 2026-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0140_simcagent_agent_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcprofile',
            name='gear_crit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simcprofile',
            name='gear_haste',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simcprofile',
            name='gear_mastery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simcprofile',
            name='gear_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simcprofile',
            name='gear_versatility',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
