# Generated by Django 5.2.7 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0144_simc_benchmark_aggregate_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='display_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='冻结的候选展示元数据'),
        ),
    ]
