# Generated by Django 5.2.7 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0145_simulationrun_display_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcbenchmarkexecution',
            name='display_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]