# Generated by Django 5.2.15 on 2026-08-01 17:51

from django.db import migrations, models


def mark_existing_ptr_profiles(apps, schema_editor):
    """One-time conversion of the already imported 12.1 PTR catalog.

    Runtime code never infers PTR from ``version``; after this migration the
    explicit ``use_ptr`` column is authoritative and can evolve independently.
    """
    SimcProfile = apps.get_model('botend', 'SimcProfile')
    SimcProfile.objects.filter(
        user_id__isnull=True,
        source='simc_upstream',
        version='12.1',
    ).update(use_ptr=True)


def unmark_existing_ptr_profiles(apps, schema_editor):
    SimcProfile = apps.get_model('botend', 'SimcProfile')
    SimcProfile.objects.filter(
        user_id__isnull=True,
        source='simc_upstream',
        version='12.1',
    ).update(use_ptr=False)


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0146_simcbenchmarkexecution_display_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcprofile',
            name='use_ptr',
            field=models.BooleanField(default=False, help_text='模拟时使用 PTR 数据库'),
        ),
        migrations.RunPython(mark_existing_ptr_profiles, unmark_existing_ptr_profiles),
    ]
