# Generated by Django 5.2.16 on 2026-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0154_dashboard_page_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcbenchmarkcandidate',
            name='effect',
            field=models.TextField(blank=True, default=''),
        ),
    ]
