# Generated by Django 5.2.16 on 2026-08-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0156_simcaplsymbol_localization_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcapl',
            name='source',
            field=models.CharField(choices=[('simc_upstream', 'SimC源码同步'), ('simc_builtin', 'SimC内置APL'), ('user', '用户维护')], default='user', help_text='内容来源', max_length=32),
        ),
    ]
