# Generated by Django 5.2.16 on 2026-08-11 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0158_unversioned_simc_apl_symbols'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcTaskFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_relations', to='botend.simctask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simc_task_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simc_task_favorite',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='simctaskfav_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'task'), name='unique_simc_task_favorite')],
            },
        ),
    ]
