# Generated by Django 5.2.13 on 2026-08-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0160_repair_wowhead_live_title_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mythicdungeonroute',
            name='share_code',
        ),
    ]
