# Generated by Django 5.2.16 on 2026-08-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0162_canonicalize_simc_mastery_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcbackendbinary',
            name='local_worker_enabled',
            field=models.BooleanField(default=True, help_text='本地Worker是否接收新任务'),
        ),
    ]
