# Generated by Django 5.2.16 on 2026-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0163_simcbackendbinary_local_worker_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcprofile',
            name='profile_set',
            field=models.CharField(default='MID1', help_text='SimC 上游 Profile 集合，如 MID1/MID2', max_length=16),
        ),
    ]
