# Generated by Django 5.2.16 on 2026-08-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0165_simcbenchmarkpanel_benchmark_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcbenchmarkpanel',
            name='comparison_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
