# Generated by Django 5.2.16 on 2026-08-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0166_simcbenchmarkpanel_comparison_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimcBenchmarkPurgeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id_snapshot', models.BigIntegerField()),
                ('panel_name', models.CharField(max_length=200)),
                ('requested_by_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('cleanup_pending', 'Cleanup Pending'), ('cleaning', 'Cleaning'), ('restore_pending', 'Restore Pending'), ('restoring', 'Restoring'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('fingerprint', models.CharField(max_length=64)),
                ('batch_id', models.CharField(max_length=40, unique=True)),
                ('plan', models.JSONField(default=dict)),
                ('quarantine_map', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claim_token', models.CharField(blank=True, default='', max_length=64)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purge_tasks', to='botend.simcbenchmarkpanel')),
            ],
            options={
                'db_table': 'simc_benchmark_purge_task',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='simc_bench_purge_q_idx')],
            },
        ),
    ]
