# Generated by Django 5.2.16 on 2026-08-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0167_simcbenchmarkpurgetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='simctask',
            name='talent_version',
            field=models.ForeignKey(blank=True, help_text='天赋字符串版本快照', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='talent_tasks', to='botend.simcresourceversion'),
        ),
        migrations.AlterField(
            model_name='simcresourceversion',
            name='resource_type',
            field=models.CharField(help_text='资源类型: profile/template/apl/talent', max_length=20),
        ),
        migrations.CreateModel(
            name='SimcTalentString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spec', models.CharField(default='fury', max_length=100)),
                ('talent', models.CharField(max_length=2000)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_selectable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'simc_talent_string',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['spec', 'is_active', 'is_selectable'], name='simc_talent_spec_03c209_idx')],
            },
        ),
        migrations.AddField(
            model_name='simctask',
            name='talent_string',
            field=models.ForeignKey(blank=True, help_text='选择的天赋字符串', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='botend.simctalentstring'),
        ),
    ]
