# Generated by Django 5.2.16 on 2026-08-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0168_simctask_talent_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcbenchmarkprofile',
            name='talent_string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_profiles', to='botend.simctalentstring'),
        ),
    ]
