# Generated by Django 5.2.16 on 2026-08-16 08:15

from django.db import migrations, models


def backfill_hero_talent_names(apps, schema_editor):
    TalentString = apps.get_model('botend', 'SimcTalentString')
    from botend.dashboard.api import _resolve_simc_talent_hero_names

    cache = {}
    for row in TalentString.objects.all().only('id', 'spec', 'talent'):
        key = (row.spec, row.talent)
        if key not in cache:
            try:
                cache[key] = list(_resolve_simc_talent_hero_names(row.spec, row.talent) or [])
            except Exception:
                cache[key] = []
        TalentString.objects.filter(pk=row.pk).update(hero_talent_names=cache[key])


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0169_simcbenchmarkprofile_talent_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='simctalentstring',
            name='hero_talent_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_hero_talent_names, migrations.RunPython.noop),
    ]
