# Generated by Django 5.2.16 on 2026-08-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0174_normalize_hero_talent_names'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='simcbenchmarkprofile',
            name='simc_bench_spec_profile_uniq',
        ),
        migrations.AddConstraint(
            model_name='simcbenchmarkprofile',
            constraint=models.UniqueConstraint(fields=('panel_spec', 'profile', 'talent_string'), name='simc_bench_spec_profile_talent_uniq'),
        ),
    ]
