# Generated by Django 5.2.16 on 2026-08-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0175_remove_simcbenchmarkprofile_simc_bench_spec_profile_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simctalentstring',
            name='system_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
