# Generated by Django 5.2.16 on 2026-08-18 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0176_simc_talent_string_system_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcbenchmarkprofile',
            name='apl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_profiles', to='botend.simcapl'),
        ),
        migrations.AddField(
            model_name='simctalentstring',
            name='default_apl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_talent_strings', to='botend.simcapl'),
        ),
    ]
