# Generated by Django 5.2.16 on 2026-08-18 05:17

from django.db import migrations, models


def backfill_benchmark_task_queue_priority(apps, schema_editor):
    SimcTask = apps.get_model('botend', 'SimcTask')
    SimcBenchmarkCase = apps.get_model('botend', 'SimcBenchmarkCase')
    benchmark_task_ids = SimcBenchmarkCase.objects.values_list('task_id', flat=True)
    SimcTask.objects.filter(pk__in=benchmark_task_ids).update(
        queue_priority=20,
        is_benchmark_task=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0178_benchmark_spec_additional_simc_input'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simctask',
            name='simctask_owner_queue_idx',
        ),
        migrations.AddField(
            model_name='simcbenchmarkpanel',
            name='queue_priority',
            field=models.PositiveSmallIntegerField(default=20, help_text='Benchmark 队列优先级；创建 Execution 时冻结到其 Task，始终低于普通模拟。'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='queue_priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='领取队列优先级；普通模拟固定为最高值，Benchmark 创建时冻结'),
        ),
        migrations.AddField(
            model_name='simctask',
            name='is_benchmark_task',
            field=models.BooleanField(default=False, help_text='仅 Benchmark Execution 创建的任务；用于持久化校验队列优先级边界。'),
        ),
        migrations.AddIndex(
            model_name='simctask',
            index=models.Index(fields=['execution_owner', 'is_active', 'current_status', '-queue_priority', 'create_time'], name='simctask_owner_queue_idx'),
        ),
        migrations.RunPython(backfill_benchmark_task_queue_priority, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='simctask',
            constraint=models.CheckConstraint(
                condition=(models.Q(is_benchmark_task=False, queue_priority=100) | models.Q(is_benchmark_task=True, queue_priority__in=(10, 20, 30))),
                name='simctask_queue_priority_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='simcbenchmarkpanel',
            constraint=models.CheckConstraint(
                condition=models.Q(queue_priority__in=(10, 20, 30)),
                name='simc_bench_queue_priority_ck',
            ),
        ),
    ]
