# Generated by Django 5.2.16 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0179_simc_task_queue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcagent',
            name='task_scope',
            field=models.CharField(
                choices=[('all', '全部任务'), ('regular_only', '仅普通模拟'), ('benchmark_only', '仅 Benchmark')],
                default='all',
                help_text='本 Agent 可领取的 Task 范围；只影响未来领取，不中断已租约 Run。',
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name='simcagent',
            constraint=models.CheckConstraint(
                condition=models.Q(task_scope__in=('all', 'regular_only', 'benchmark_only')),
                name='simc_agent_task_scope_ck',
            ),
        ),
    ]
