# Generated by Django 5.2.16 on 2026-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0180_simc_agent_task_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowspellsnapshot',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
