# Generated by Django 5.2.16 on 2026-08-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0181_wow_spell_snapshot_icon'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='specraidranking',
            name='idx_boss_spec',
        ),
        migrations.AddField(
            model_name='specraidranking',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=5, help_text='WCL difficulty：4=Heroic，5=Mythic', verbose_name='难度'),
        ),
        migrations.AddIndex(
            model_name='specraidranking',
            index=models.Index(fields=['season_id', 'boss_id', 'difficulty', 'class_name', 'spec_name'], name='idx_boss_diff_spec'),
        ),
    ]
