# Generated by Django 5.2.13 on 2026-08-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0183_simc_skill_damage_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythicDungeonDefaultRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('dungeon_level', models.PositiveIntegerField(default=10)),
                ('route_data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_routes', to='botend.mythicdungeon')),
            ],
            options={
                'db_table': 'mythic_dungeon_default_route',
                'ordering': ['-is_featured', 'order', 'name', 'id'],
                'indexes': [models.Index(fields=['dungeon', 'is_active', 'order'], name='md_default_dungeon_idx'), models.Index(fields=['is_featured', 'is_active'], name='md_default_featured_idx')],
            },
        ),
    ]
