# Generated by Django 5.2.13 on 2026-09-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0192_wow_today_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowTodaySectionSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=128, unique=True)),
                ('source_name', models.CharField(blank=True, default='', max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_today_section_setting',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['is_visible', 'sort_order'], name='wow_today_setting_order_idx')],
            },
        ),
    ]
