# Generated by Django 5.2.13 on 2026-09-03 07:04

import hashlib
import django.db.models.deletion
from django.db import migrations, models


def _stable_key(value, prefix, seed):
    key = str(value or '').strip()
    if key:
        return key[:128]
    digest = hashlib.sha1(str(seed or prefix).encode('utf-8')).hexdigest()[:16]
    return f'{prefix}-{digest}'


def backfill_wow_today_cards(apps, schema_editor):
    Snapshot = apps.get_model('botend', 'WowTodaySnapshot')
    SectionSetting = apps.get_model('botend', 'WowTodaySectionSetting')
    CardSnapshot = apps.get_model('botend', 'WowTodayCardSnapshot')
    CardSetting = apps.get_model('botend', 'WowTodayCardSetting')

    for snapshot in Snapshot.objects.order_by('snapshot_date', 'fetched_at', 'id').iterator():
        sections = snapshot.sections_json if isinstance(snapshot.sections_json, list) else []
        card_rows = []
        for section_index, section in enumerate(sections):
            if not isinstance(section, dict):
                continue
            source_section_name = str(section.get('name') or '').strip()[:150]
            section_key = _stable_key(
                section.get('key') or section.get('id'),
                'section',
                source_section_name,
            )
            default_visible = not (
                source_section_name.lower() in {'quests', 'economy', '任务', '经济'}
                or section_key.lower().startswith(('quests', 'economy'))
            )
            section_setting, _ = SectionSetting.objects.get_or_create(
                section_key=section_key,
                defaults={
                    'source_name': source_section_name,
                    'is_visible': default_visible,
                    'sort_order': (section_index + 1) * 10,
                },
            )
            if section_setting.source_name != source_section_name:
                section_setting.source_name = source_section_name
                section_setting.save(update_fields=('source_name', 'updated_at'))

            modules = section.get('modules') if isinstance(section.get('modules'), list) else []
            visible_card_index = 0
            for card_index, card in enumerate(modules):
                if not isinstance(card, dict):
                    continue
                kind = str(card.get('kind') or card.get('type') or 'lines').strip().lower()[:40]
                if kind == 'mythic-progression':
                    continue
                source_name = str(card.get('name') or '').strip()[:150]
                card_key = _stable_key(
                    card.get('key') or card.get('id'),
                    'card',
                    f'{section_key}:{source_name}',
                )
                visible_card_index += 1
                card_rows.append(CardSnapshot(
                    snapshot=snapshot,
                    section_key=section_key,
                    section_name=source_section_name,
                    section_order=(section_index + 1) * 10,
                    card_key=card_key,
                    source_name=source_name,
                    kind=kind or 'lines',
                    source_url=str(card.get('url') or '').strip()[:500],
                    payload_json=dict(card),
                    card_order=visible_card_index * 10,
                ))
                card_setting, _ = CardSetting.objects.get_or_create(
                    section_key=section_key,
                    card_key=card_key,
                    defaults={
                        'source_name': source_name,
                        'sort_order': visible_card_index * 10,
                    },
                )
                if card_setting.source_name != source_name:
                    card_setting.source_name = source_name
                    card_setting.save(update_fields=('source_name', 'updated_at'))
        if card_rows:
            CardSnapshot.objects.bulk_create(card_rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0193_wowtodaysectionsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowTodayCardSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=128)),
                ('card_key', models.CharField(max_length=128)),
                ('source_name', models.CharField(blank=True, default='', max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_today_card_setting',
                'ordering': ('section_key', 'sort_order', 'id'),
                'indexes': [models.Index(fields=['section_key', 'is_visible', 'sort_order'], name='wow_tiw_card_set_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('section_key', 'card_key'), name='uniq_wow_today_card_setting')],
            },
        ),
        migrations.CreateModel(
            name='WowTodayCardSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=128)),
                ('section_name', models.CharField(blank=True, default='', max_length=150)),
                ('section_order', models.PositiveIntegerField(default=100)),
                ('card_key', models.CharField(max_length=128)),
                ('source_name', models.CharField(blank=True, default='', max_length=150)),
                ('kind', models.CharField(blank=True, default='lines', max_length=40)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('card_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_snapshots', to='botend.wowtodaysnapshot')),
            ],
            options={
                'db_table': 'wow_today_card_snapshot',
                'ordering': ('section_order', 'card_order', 'id'),
                'indexes': [models.Index(fields=['snapshot', 'section_order', 'card_order'], name='wow_tiw_card_snap_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'section_key', 'card_key'), name='uniq_wow_today_snapshot_card')],
            },
        ),
        migrations.RunPython(backfill_wow_today_cards, migrations.RunPython.noop),
    ]
