# Generated by Django 5.2.13 on 2026-09-03 09:30

import hashlib
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


GROUP_META = {
    'today': ('今日动态', '重置、活动与当天重点', 'calendar', 10),
    'data': ('职业与数据', '专精页面与模拟结果', 'chart', 20),
    'mythic': ('大秘境数据', '分数线、巅峰榜与热门排行', 'refresh', 30),
    'tools': ('玩家工具', '天赋、配装与路线规划', 'tools', 40),
    'community': ('内容社区', '新闻、讨论与视频攻略', 'newspaper', 50),
}


def split_internal_navigation(apps, schema_editor):
    PortalToolLink = apps.get_model('botend', 'PortalToolLink')
    PortalNavigationGroup = apps.get_model('botend', 'PortalNavigationGroup')
    PortalNavigationItem = apps.get_model('botend', 'PortalNavigationItem')
    internal_links = list(
        PortalToolLink.objects.filter(Q(url__startswith='/') | Q(url__startswith='#'))
        .order_by('topbar_order', 'sort_order', 'id')
    )
    group_keys = []
    for row in internal_links:
        key = (row.category or 'tools').strip() or 'tools'
        if key not in group_keys:
            group_keys.append(key)
    for fallback_index, key in enumerate(group_keys, start=1):
        name, description, icon_key, default_order = GROUP_META.get(
            key,
            (key, '自定义站内入口分组', 'globe', 100 + fallback_index * 10),
        )
        group, _ = PortalNavigationGroup.objects.update_or_create(
            key=key,
            defaults={
                'name': name,
                'description': description,
                'icon_key': icon_key,
                'sort_order': default_order,
                'is_active': True,
            },
        )
        for row in (item for item in internal_links if ((item.category or 'tools').strip() or 'tools') == key):
            PortalNavigationItem.objects.create(
                group=group,
                name=row.name,
                url=row.url,
                desc=row.desc or '',
                icon_key=row.icon_key or '',
                badge=row.badge or '',
                badge_tone=row.badge_tone or 'default',
                sort_order=row.topbar_order or row.sort_order or 0,
                show_in_header=bool(row.is_topbar),
                show_in_home_guide=bool(row.show_in_guide),
                is_active=bool(row.is_active),
            )
    PortalToolLink.objects.filter(Q(url__startswith='/') | Q(url__startswith='#')).delete()


def merge_internal_navigation(apps, schema_editor):
    PortalToolLink = apps.get_model('botend', 'PortalToolLink')
    PortalNavigationGroup = apps.get_model('botend', 'PortalNavigationGroup')
    for group in PortalNavigationGroup.objects.all().prefetch_related('items'):
        for item in group.items.all():
            url_hash = hashlib.sha256(item.url.encode('utf-8')).hexdigest()
            PortalToolLink.objects.update_or_create(
                url_hash=url_hash,
                defaults={
                    'name': item.name,
                    'url': item.url,
                    'desc': item.desc,
                    'source': 'wowdaily',
                    'category': group.key,
                    'icon_key': item.icon_key,
                    'badge': item.badge,
                    'badge_tone': item.badge_tone,
                    'sort_order': item.sort_order,
                    'is_topbar': item.show_in_header,
                    'topbar_order': item.sort_order,
                    'show_in_guide': item.show_in_home_guide,
                    'show_in_tools': False,
                    'open_in_new_tab': False,
                    'icon_path': '',
                    'is_active': item.is_active,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0197_portal_mythic_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalNavigationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('icon_key', models.CharField(blank=True, default='globe', max_length=48)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_portal_navigation_group',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='wow_portal__is_acti_e6ba79_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortalNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('desc', models.CharField(blank=True, default='', max_length=500)),
                ('icon_key', models.CharField(blank=True, default='', max_length=48)),
                ('badge', models.CharField(blank=True, default='', max_length=32)),
                ('badge_tone', models.CharField(choices=[('default', '常规'), ('new', '新内容（红色）')], default='default', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('show_in_header', models.BooleanField(default=False)),
                ('show_in_home_guide', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='botend.portalnavigationgroup')),
            ],
            options={
                'db_table': 'wow_portal_navigation_item',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['group', 'is_active', 'sort_order'], name='wow_portal__group_i_a53725_idx'), models.Index(fields=['show_in_header', 'is_active'], name='wow_portal__show_in_819f54_idx'), models.Index(fields=['show_in_home_guide', 'is_active'], name='wow_portal__show_in_32ea94_idx')],
            },
        ),
        migrations.RunPython(split_internal_navigation, merge_internal_navigation),
    ]
