# Generated by Django 5.2.16 on 2026-09-03 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0201_unify_portal_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTaskLease',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='execution_lease', serialize=False, to='botend.monitortask')),
                ('owner', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
