# Generated by Django 5.2.16 on 2026-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0207_move_nga_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowarticle',
            name='nga_board_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='nga_board_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wowarticle',
            name='nga_replies_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
