# Generated by Django 5.2.16 on 2026-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0226_disable_adventure_journal_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowtalentversion',
            name='granted_entries_json',
            field=models.JSONField(blank=True, default=dict, help_text='同 build TraitCond 赠送天赋：spec ID → TraitNodeEntry.ID 列表'),
        ),
    ]
