# Generated by Django 5.2.16 on 2026-09-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0227_talent_granted_entries'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wowhotfixreport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wowwagohotfixevent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wowhotfixreport',
            name='class_class_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wowhotfixreport',
            name='class_content_html_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wowhotfixreport',
            name='class_spell_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wowhotfixreport',
            name='class_unresolved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wowhotfixreport',
            name='collection_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wowhotfixreport',
            name='region_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wowhotfixreport',
            name='source_facts_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wowwagohotfixevent',
            name='region_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='wowhotfixreport',
            unique_together={('branch', 'locale', 'region_id', 'to_push')},
        ),
        migrations.AlterUniqueTogether(
            name='wowwagohotfixevent',
            unique_together={('branch', 'locale', 'region_id', 'to_push')},
        ),
    ]
