# Generated by Django 5.2.16 on 2026-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0235_monitor_task_default_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowRealmDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=128)),
                ('localized_name', models.CharField(blank=True, default='', max_length=128)),
                ('locale', models.CharField(max_length=10)),
                ('source_url', models.URLField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wow_realm_directory',
                'constraints': [models.UniqueConstraint(fields=('region', 'slug'), name='wow_realm_region_slug_unique')],
            },
        ),
    ]
