# Generated by Django 5.2.16 on 2026-10-10 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botend', '0236_wow_realm_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WclCombatantSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=50)),
                ('fight_id', models.PositiveIntegerField()),
                ('actor_id', models.PositiveIntegerField()),
                ('payload_json', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wow_wcl_combatant_snapshot',
                'constraints': [models.UniqueConstraint(fields=('report_code', 'fight_id', 'actor_id'), name='uniq_wcl_combatant_actor')],
            },
        ),
    ]
