"""Secure registration of Worker-produced SimC report artifacts."""
import os
import re
from pathlib import Path

from django.conf import settings
from django.db import transaction

from botend.models import SimcTask, SimcTaskArtifact
from botend.services.simc_attribute_results import parse_attribute_result_filename


_REGULAR_RESULT_NAME_RE = re.compile(r"^simc_task_(?P<task_id>\d+)\.html$")
_UUID_RESULT_NAME_RE = re.compile(r"^(?P<uuid>[0-9a-f]{32})\.html$")
_RUN_RESULT_NAME_RE = re.compile(r"^(?P<base>.+)_run_(?P<run_id>\d+)\.html$")


def _task_result_base(task):
    """Return the stable task-owned basename used to derive immutable Run reports."""
    filename = str(task.result_file or "").strip()
    run_match = _RUN_RESULT_NAME_RE.fullmatch(filename)
    if run_match:
        filename = f"{run_match.group('base')}.html"
    regular_match = _REGULAR_RESULT_NAME_RE.fullmatch(filename)
    if regular_match and int(regular_match.group("task_id")) == int(task.pk):
        return filename[:-5]
    if _UUID_RESULT_NAME_RE.fullmatch(filename):
        return filename[:-5]
    return None


def result_filename_for_run(task, run):
    """Allocate the deterministic physical report name owned by one Task/Run pair."""
    if run is None or int(run.task_id) != int(task.pk):
        return None
    base = _task_result_base(task)
    if not base:
        return None
    return f"{base}_run_{run.pk}.html"


def _validated_result(task, result_file, run=None):
    """Return (absolute path, static-relative path) for this task's generated report."""
    filename = str(result_file or "").strip()
    if not filename or filename != os.path.basename(filename) or "\n" in filename or "\r" in filename:
        return None

    if run is not None:
        if filename != result_filename_for_run(task, run):
            return None
    else:
        regular_match = _REGULAR_RESULT_NAME_RE.fullmatch(filename)
        attribute_result = parse_attribute_result_filename(filename)
        bound_id = regular_match.group("task_id") if regular_match else None
        if attribute_result:
            bound_id = attribute_result["task_id"]
        uuid_owned = bool(
            _UUID_RESULT_NAME_RE.fullmatch(filename)
            and filename == str(task.result_file or "").strip()
        )
        if not uuid_owned and (not bound_id or int(bound_id) != int(task.pk)):
            return None

    result_root = (Path(settings.BASE_DIR) / "static" / "simc_results").resolve()
    full_path = (result_root / filename).resolve()
    try:
        full_path.relative_to(result_root)
    except ValueError:
        return None
    if not full_path.is_file():
        return None
    return full_path, f"simc_results/{filename}"


def upsert_task_html_artifact(task, result_file, run=None):
    """Atomically register an existing, task-id-bound report generated in the result root.

    The caller cannot choose a directory, another task's filename, or a non-report file.
    Locking the owner task makes the application-level upsert deterministic even though the
    legacy artifact table has no uniqueness constraint.
    """
    # A Run can never register an artifact through a different Task, even when
    # a caller supplies an otherwise valid-looking path.
    if run is not None and int(run.task_id) != int(task.pk):
        return None
    validated = _validated_result(task, result_file, run=run)
    if not validated:
        return None
    full_path, relative_path = validated
    with transaction.atomic():
        locked_task = SimcTask.objects.select_for_update().filter(pk=task.pk, user_id=task.user_id).first()
        if not locked_task:
            return None
        artifact_query = SimcTaskArtifact.objects.filter(
            task=locked_task, artifact_type="html_report", file_path=relative_path,
        )
        # A report generated by a new execution belongs to that immutable Run.
        # Never reassign an older Run's artifact merely because the task-bound
        # filename is reused by a later execution.
        if run is not None:
            artifact_query = artifact_query.filter(run=run)
        artifact = artifact_query.order_by("id").first()
        size = full_path.stat().st_size
        if artifact and run is None and artifact.file_size != size:
            # Preserve the legacy compatibility upsert for task-level artifacts.
            # Run-bound artifacts are immutable once published.
            artifact.file_size = size
            artifact.save(update_fields=["file_size"])
        elif not artifact:
            artifact = SimcTaskArtifact.objects.create(
                task=locked_task, run=run, artifact_type="html_report",
                file_path=relative_path, file_size=size,
            )
        return artifact


def map_existing_successful_task_artifact(task):
    """Strict compatibility mapping for an owner's historical regular result."""
    if task.current_status != 2:
        return None
    return upsert_task_html_artifact(task, task.result_file)
