# -*- coding: utf-8 -*-
"""
WoW 职业专精常量
"""

# 职业 → 专精列表
CLASS_SPEC_MAP = {
    "DeathKnight": ["Blood", "Frost", "Unholy"],
    "DemonHunter": ["Havoc", "Vengeance", "Devourer"],
    "Druid":       ["Balance", "Feral", "Guardian", "Restoration"],
    "Hunter":      ["BeastMastery", "Marksmanship", "Survival"],
    "Mage":        ["Arcane", "Fire", "Frost"],
    "Monk":        ["Brewmaster", "Mistweaver", "Windwalker"],
    "Paladin":     ["Holy", "Protection", "Retribution"],
    "Priest":      ["Discipline", "Holy", "Shadow"],
    "Rogue":       ["Assassination", "Outlaw", "Subtlety"],
    "Shaman":      ["Elemental", "Enhancement", "Restoration"],
    "Warrior":     ["Arms", "Fury", "Protection"],
    "Warlock":     ["Affliction", "Demonology", "Destruction"],
    "Evoker":      ["Augmentation", "Devastation", "Preservation"],
}

# Blizzard specialization ID → (职业, 专精)。天赋导入字符串头部直接存储该 ID。
SPEC_IDENTITY_MAP = {
    62: ("Mage", "Arcane"),
    63: ("Mage", "Fire"),
    64: ("Mage", "Frost"),
    65: ("Paladin", "Holy"),
    66: ("Paladin", "Protection"),
    70: ("Paladin", "Retribution"),
    71: ("Warrior", "Arms"),
    72: ("Warrior", "Fury"),
    73: ("Warrior", "Protection"),
    102: ("Druid", "Balance"),
    103: ("Druid", "Feral"),
    104: ("Druid", "Guardian"),
    105: ("Druid", "Restoration"),
    250: ("DeathKnight", "Blood"),
    251: ("DeathKnight", "Frost"),
    252: ("DeathKnight", "Unholy"),
    253: ("Hunter", "BeastMastery"),
    254: ("Hunter", "Marksmanship"),
    255: ("Hunter", "Survival"),
    256: ("Priest", "Discipline"),
    257: ("Priest", "Holy"),
    258: ("Priest", "Shadow"),
    259: ("Rogue", "Assassination"),
    260: ("Rogue", "Outlaw"),
    261: ("Rogue", "Subtlety"),
    262: ("Shaman", "Elemental"),
    263: ("Shaman", "Enhancement"),
    264: ("Shaman", "Restoration"),
    265: ("Warlock", "Affliction"),
    266: ("Warlock", "Demonology"),
    267: ("Warlock", "Destruction"),
    268: ("Monk", "Brewmaster"),
    269: ("Monk", "Windwalker"),
    270: ("Monk", "Mistweaver"),
    577: ("DemonHunter", "Havoc"),
    581: ("DemonHunter", "Vengeance"),
    1467: ("Evoker", "Devastation"),
    1468: ("Evoker", "Preservation"),
    1473: ("Evoker", "Augmentation"),
    1480: ("DemonHunter", "Devourer"),
}

# 英文职业名 → 中文
CLASS_CN = {
    "DeathKnight": "死亡骑士",
    "DemonHunter": "恶魔猎手",
    "Druid":       "德鲁伊",
    "Hunter":      "猎人",
    "Mage":        "法师",
    "Monk":        "武僧",
    "Paladin":     "圣骑士",
    "Priest":      "牧师",
    "Rogue":       "潜行者",
    "Shaman":      "萨满祭司",
    "Warrior":     "战士",
    "Warlock":     "术士",
    "Evoker":      "唤魔师",
}

# 英文专精名 → 中文（同名专精只列一次，如 Frost 同时是 DK 和 Mage 的）
SPEC_CN = {
    "Blood":          "鲜血",
    "Frost":          "冰霜",
    "Unholy":         "邪恶",
    "Havoc":          "浩劫",
    "Vengeance":      "复仇",
    "Balance":        "平衡",
    "Feral":          "野性",
    "Guardian":       "守护",
    "Restoration":    "恢复",
    "BeastMastery":   "野兽控制",
    "Marksmanship":   "射击",
    "Survival":       "生存",
    "Arcane":         "奥术",
    "Fire":           "火焰",
    "Brewmaster":     "酒仙",
    "Mistweaver":     "织雾",
    "Windwalker":     "踏风",
    "Holy":           "神圣",
    "Protection":     "防护",
    "Retribution":    "惩戒",
    "Discipline":     "戒律",
    "Shadow":         "暗影",
    "Assassination":  "奇袭",
    "Outlaw":         "狂徒",
    "Subtlety":       "敏锐",
    "Elemental":      "元素",
    "Enhancement":    "增强",
    "Arms":           "武器",
    "Fury":           "狂怒",
    "Affliction":     "痛苦",
    "Demonology":     "恶魔学识",
    "Destruction":    "毁灭",
    "Augmentation":   "增辉",
    "Devastation":    "湮灭",
    "Preservation":   "恩护",
}

# (职业, 专精) → 角色
SPEC_ROLE = {
    ("DeathKnight", "Blood"):         "tank",
    ("DeathKnight", "Frost"):         "dps",
    ("DeathKnight", "Unholy"):        "dps",
    ("DemonHunter", "Havoc"):         "dps",
    ("DemonHunter", "Vengeance"):     "tank",
    ("Druid", "Balance"):             "dps",
    ("Druid", "Feral"):               "dps",
    ("Druid", "Guardian"):            "tank",
    ("Druid", "Restoration"):         "healer",
    ("Hunter", "BeastMastery"):       "dps",
    ("Hunter", "Marksmanship"):       "dps",
    ("Hunter", "Survival"):           "dps",
    ("Mage", "Arcane"):               "dps",
    ("Mage", "Fire"):                 "dps",
    ("Mage", "Frost"):                "dps",
    ("Monk", "Brewmaster"):           "tank",
    ("Monk", "Mistweaver"):           "healer",
    ("Monk", "Windwalker"):           "dps",
    ("Paladin", "Holy"):              "healer",
    ("Paladin", "Protection"):        "tank",
    ("Paladin", "Retribution"):       "dps",
    ("Priest", "Discipline"):         "healer",
    ("Priest", "Holy"):               "healer",
    ("Priest", "Shadow"):             "dps",
    ("Rogue", "Assassination"):       "dps",
    ("Rogue", "Outlaw"):              "dps",
    ("Rogue", "Subtlety"):            "dps",
    ("Shaman", "Elemental"):          "dps",
    ("Shaman", "Enhancement"):        "dps",
    ("Shaman", "Restoration"):        "healer",
    ("Warrior", "Arms"):              "dps",
    ("Warrior", "Fury"):              "dps",
    ("Warrior", "Protection"):        "tank",
    ("Warlock", "Affliction"):        "dps",
    ("Warlock", "Demonology"):        "dps",
    ("Warlock", "Destruction"):       "dps",
    ("Evoker", "Augmentation"):       "dps",
    ("Evoker", "Devastation"):        "dps",
    ("Evoker", "Preservation"):       "healer",
}

# (职业, 专精) → Wowhead CDN 图标 URL
SPEC_ICON = {
    ("DeathKnight", "Blood"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_deathknight_bloodpresence.jpg",
    ("DeathKnight", "Frost"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_deathknight_frostpresence.jpg",
    ("DeathKnight", "Unholy"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_deathknight_unholypresence.jpg",
    ("DemonHunter", "Havoc"):         "https://wow.zamimg.com/images/wow/icons/medium/ability_demonhunter_specdps.jpg",
    ("DemonHunter", "Vengeance"):     "https://wow.zamimg.com/images/wow/icons/medium/ability_demonhunter_spectank.jpg",
    ("Druid", "Balance"):             "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_starfall.jpg",
    ("Druid", "Feral"):               "https://wow.zamimg.com/images/wow/icons/medium/ability_druid_catform.jpg",
    ("Druid", "Guardian"):            "https://wow.zamimg.com/images/wow/icons/medium/ability_racial_bearform.jpg",
    ("Druid", "Restoration"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_healingtouch.jpg",
    ("Hunter", "BeastMastery"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_hunter_bestialdiscipline.jpg",
    ("Hunter", "Marksmanship"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_hunter_focusedaim.jpg",
    ("Hunter", "Survival"):           "https://wow.zamimg.com/images/wow/icons/medium/ability_hunter_camouflage.jpg",
    ("Mage", "Arcane"):               "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_magicalsentry.jpg",
    ("Mage", "Fire"):                 "https://wow.zamimg.com/images/wow/icons/medium/spell_fire_firebolt02.jpg",
    ("Mage", "Frost"):                "https://wow.zamimg.com/images/wow/icons/medium/spell_frost_frostbolt02.jpg",
    ("Monk", "Brewmaster"):           "https://wow.zamimg.com/images/wow/icons/medium/monk_stance_drunkenox.jpg",
    ("Monk", "Mistweaver"):           "https://wow.zamimg.com/images/wow/icons/medium/spell_monk_mistweaver_spec.jpg",
    ("Monk", "Windwalker"):           "https://wow.zamimg.com/images/wow/icons/medium/monk_stance_whitetiger.jpg",
    ("Paladin", "Holy"):              "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_holybolt.jpg",
    ("Paladin", "Protection"):        "https://wow.zamimg.com/images/wow/icons/medium/ability_paladin_shieldofthetemplar.jpg",
    ("Paladin", "Retribution"):       "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_auraoflight.jpg",
    ("Priest", "Discipline"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_powerwordshield.jpg",
    ("Priest", "Holy"):               "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_guardianspirit.jpg",
    ("Priest", "Shadow"):             "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_shadowwordpain.jpg",
    ("Rogue", "Assassination"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_eviscerate.jpg",
    ("Rogue", "Outlaw"):              "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_waylay.jpg",
    ("Rogue", "Subtlety"):            "https://wow.zamimg.com/images/wow/icons/medium/ability_stealth.jpg",
    ("Shaman", "Elemental"):          "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_lightning.jpg",
    ("Shaman", "Enhancement"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_shaman_improvedstormstrike.jpg",
    ("Shaman", "Restoration"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_magicimmunity.jpg",
    ("Warrior", "Arms"):              "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_savageblow.jpg",
    ("Warrior", "Fury"):              "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_innerrage.jpg",
    ("Warrior", "Protection"):        "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_defensivestance.jpg",
    ("Warlock", "Affliction"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_deathcoil.jpg",
    ("Warlock", "Demonology"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_metamorphosis.jpg",
    ("Warlock", "Destruction"):       "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_rainoffire.jpg",
    ("Evoker", "Augmentation"):       "https://wow.zamimg.com/images/wow/icons/medium/classicon_evoker_augmentation.jpg",
    ("Evoker", "Devastation"):        "https://wow.zamimg.com/images/wow/icons/medium/classicon_evoker_devastation.jpg",
    ("Evoker", "Preservation"):       "https://wow.zamimg.com/images/wow/icons/medium/classicon_evoker_preservation.jpg",
}

# ========== 副本/团本 中文名 ==========

DUNGEON_CN = {
    # TWW Season 1
    "Ara-Kara, City of Echoes": "阿拉卡拉，回声之城",
    "City of Threads": "千丝之城",
    "Grim Batol": "格瑞姆巴托",
    "Mists of Tirna Scithe": "塞兹仙林的迷雾",
    "Necrotic Wake": "通灵战潮",
    "Siege of Boralus": "围攻伯拉勒斯",
    "Stonevault": "矶石宝库",
    "The Dawnbreaker": "破晨号",
    # TWW Season 2/3
    "Algeth'ar Academy": "艾杰斯亚学院",
    "Magisters' Terrace": "魔导师平台",
    "Maisara Caverns": "迈萨拉洞窟",
    "Nexus-Point Xenas": "节点希纳斯",
    "Pit of Saron": "萨隆矿坑",
    "Seat of the Triumvirate": "执政团之座",
    "Skyreach": "通天峰",
    "Windrunner Spire": "风行者之塔",
    # 其他可能复用的副本
    "Mechagon Workshop": "麦卡贡车间",
    "Tazavesh, Veiled Market": "塔扎维什·帷纱集市",
    "Tazavesh: So'leah's Gambit": "塔扎维什·索莉亚的豪赌",
    "Tazavesh: Streets of Wonder": "塔扎维什·奇街巷",
    "The Rookery": "育婴堂",
    "Darkflame Cleft": "暗焰裂口",
    "Cinderbrew Meadery": "余烬酿酒厂",
    "The Stonevault": "矶石宝库",
}

# 团本区域英文 → 中文
RAID_ZONE_CN = {
    # TWW
    "Nerub-ar Palace": "尼鲁巴尔王宫",
    "Liberation of Undermine": "安德麦解放战",
    "Manaforge Omega": "法力熔炉：欧米伽",
    # MN S1
    "VS / DR / MQD": "虚影尖塔 / 梦境裂隙 / 进攻奎尔丹纳斯",
    "Sporefall": "腐沼幽境",
}

RAID_BOSS_CN = {
    # Nerub-ar Palace (尼鲁巴尔王宫)
    "Ulgrax the Devourer": "吞噬者乌格拉克斯",
    "The Bloodbound Horror": "血缚恐惧",
    "Sikran, Captain of the Sureki": "苏雷吉队长席克拉",
    "Rasha'nan": "拉夏南",
    "Broodtwister Ovi'nax": "虫巢扭曲者欧维纳克斯",
    "Nexus-Princess Ky'veza": "节点女亲王凯威扎",
    "The Silken Court": "蛛丝议会",
    "Queen Ansurek": "安苏雷克女王",
    # Liberation of Undermine (安德麦解放战)
    "Vexie and the Geargrinders": "维克茜和磨轮",
    "Cauldron of Carnage": "残杀战炉",
    "Rik Reverb": "里克·混响",
    "Stix Bunkjunker": "斯提克斯·堆渣",
    "Sprocketmonger Lockenstock": "链齿狂人洛肯斯托克",
    "The One-Armed Bandit": "独臂盗匪",
    "Mug'Zee, Heads of Security": "穆格·兹奇，安保头子",
    "Chrome King Gallywix": "铬金大王加里维克斯",
    # Manaforge Omega (法力熔炉：欧米伽)
    "Plexus Sentinel": "丛网哨兵",
    "Loom'ithar": "织缕者伊萨尔",
    "Soulbinder Naazindhri": "缚魂者纳兹因德丽",
    "Forgeweaver Araz": "锻织者阿拉兹",
    "The Soul Hunters": "猎魂者",
    "Fractillus": "碎裂者",
    "Nexus-King Salhadaar": "节点之王萨哈达尔",
    "Dimensius, the All-Devouring": "万噬者迪曼修斯",
    # MN S1 (午夜之殿)
    "Imperator Averzian": "元首阿福扎恩",
    "Vorasius": "弗拉希乌斯",
    "Fallen-King Salhadaar": "陨落之王萨哈达尔",
    "Vaelgor & Ezzorak": "威厄高尔与艾佐拉克",
    "Lightblinded Vanguard": "战争牧师瑟恩",
    "Crown of the Cosmos": "宇宙之冠",
    "Chimaerus, the Undreamt God": "奇美鲁斯",
    "Belo'ren, Child of Al'ar": "贝洛朗",
    "Midnight Falls": "至暗之夜降临",
    # Sporefall (腐沼幽境)
    "Rotmire": "腐沼",
}

# 装备槽位英文 → 中文
SLOT_CN = {
    "head": "头盔", "neck": "项链", "shoulder": "肩甲", "back": "披风",
    "chest": "胸甲", "shirt": "衬衫", "tabard": "战袍", "wrist": "护腕",
    "hands": "手套", "waist": "腰带", "legs": "腿甲", "feet": "靴子",
    "finger1": "戒指1", "finger2": "戒指2",
    "trinket1": "饰品1", "trinket2": "饰品2",
    "mainHand": "主手", "offHand": "副手",
    "UNKNOWN": "未知", "unknown": "未知",
    # 大写格式
    "HEAD": "头盔", "NECK": "项链", "SHOULDER": "肩甲", "BACK": "披风",
    "CHEST": "胸甲", "SHIRT": "衬衫", "TABARD": "战袍", "WRIST": "护腕",
    "HANDS": "手套", "WAIST": "腰带", "LEGS": "腿甲", "FEET": "靴子",
    "FINGER_1": "戒指1", "FINGER_2": "戒指2",
    "TRINKET_1": "饰品1", "TRINKET_2": "饰品2",
    "MAIN_HAND": "主手", "OFF_HAND": "副手",
    # 下划线格式（Raider.IO / WCL）
    "main_hand": "主手", "off_hand": "副手",
}

# 种族英文 → 中文
RACE_CN = {
    "Blood Elf": "血精灵",
    "Dark Iron Dwarf": "黑铁矮人",
    "Dracthyr": "龙希尔",
    "Draenei": "德莱尼",
    "Dwarf": "矮人",
    "Gnome": "侏儒",
    "Goblin": "地精",
    "Haranir": "哈拉尼尔",
    "Highmountain Tauren": "至高岭牛头人",
    "Human": "人类",
    "Kul Tiran": "库尔提拉斯人",
    "Mag'har Orc": "玛格汉兽人",
    "Mechagnome": "机械侏儒",
    "Night Elf": "暗夜精灵",
    "Nightborne": "夜之子",
    "Orc": "兽人",
    "Pandaren": "熊猫人",
    "Tauren": "牛头人",
    "Troll": "巨魔",
    "Undead": "亡灵",
    "Void Elf": "虚无精灵",
    "Vulpera": "狐人",
    "Worgen": "狼人",
    "Zandalari Troll": "赞达拉巨魔",
}

# 附魔名称英文 → 中文（精确匹配）
ENCHANT_CN = {
    # 头盔
    "Enchant Helm - Blessing of Speed": "附魔头盔 - 速度祝福",
    "Enchant Helm - Empowered Blessing of Speed": "附魔头盔 - 强化速度祝福",
    "Enchant Helm - Hex of Leeching": "附魔头盔 - 吸血妖术",
    "Enchant Helm - Empowered Hex of Leeching": "附魔头盔 - 强化吸血妖术",
    "Enchant Helm - Rune of Avoidance": "附魔头盔 - 闪避符文",
    "Enchant Helm - Empowered Rune of Avoidance": "附魔头盔 - 强化闪避符文",
    # 肩膀
    "Enchant Shoulders - Amirdrassil's Grace": "附魔肩膀 - 阿米达希尔的恩典",
    "Enchant Shoulders - Akil'zon's Swiftness": "附魔肩膀 - 阿基尔森的迅捷",
    "Enchant Shoulders - Nature's Grace": "附魔肩膀 - 自然恩典",
    "Enchant Shoulders - Silvermoon's Mending": "附魔肩膀 - 银月治愈",
    "Enchant Shoulders - Thalassian Recovery": "附魔肩膀 - 萨拉斯复苏",
    "Enchant Shoulders - Flight of the Eagle": "附魔肩膀 - 鹰之翱翔",
    # 胸甲
    "Enchant Chest - Mark of the Worldsoul": "附魔胸甲 - 世界之魂印记",
    "Enchant Chest - Mark of Nalorakk": "附魔胸甲 - 纳洛拉克印记",
    "Enchant Chest - Mark of the Rootwarden": "附魔胸甲 - 根须守护者印记",
    # 靴子
    "Enchant Boots - Lynx's Dexterity": "附魔靴子 - 猞猁敏捷",
    "Enchant Boots - Farstrider's Hunt": "附魔靴子 - 远行者猎杀",
    "Enchant Boots - Shaladrassil's Roots": "附魔靴子 - 沙拉达希尔之根",
    # 戒指
    "Enchant Ring - Eyes of the Eagle": "附魔戒指 - 鹰眼",
    "Enchant Ring - Nature's Fury": "附魔戒指 - 自然之怒",
    "Enchant Ring - Silvermoon's Alacrity": "附魔戒指 - 银月迅敏",
    "Enchant Ring - Silvermoon's Tenacity": "附魔戒指 - 银月坚韧",
    "Enchant Ring - Thalassian Haste": "附魔戒指 - 萨拉斯急速",
    "Enchant Ring - Thalassian Vers": "附魔戒指 - 萨拉斯全能",
    "Enchant Ring - Amani Mast": "附魔戒指 - 阿曼尼精通",
    "Enchant Ring - Zul'jin's Mast": "附魔戒指 - 祖尔金的精通",
    # 武器
    "Enchant Weapon - Acuity of the Ren'dorei": "附魔武器 - 虚无精灵之敏",
    "Enchant Weapon - Arcane Mast": "附魔武器 - 奥术精通",
    "Enchant Weapon - Berserker's Rage": "附魔武器 - 狂战士之怒",
    "Enchant Weapon - Jan'alai's Precision": "附魔武器 - 姜纳莱的精准",
    "Enchant Weapon - Worldsoul Tenacity": "附魔武器 - 世界之魂坚韧",
    # 护腿
    "41 Agi/Str & 115 Sta": "41 敏捷/力量 & 115 耐力",
    "41 Agi/Str & 27 Armor": "41 敏捷/力量 & 27 护甲",
    "41 Int & 115 Sta": "41 智力 & 115 耐力",
}

# 宝石属性缩写英文 → 中文
GEM_STAT_CN = {
    "Crit": "暴击",
    "Haste": "急速",
    "Mast": "精通",
    "Vers": "全能",
    "Primary": "主属性",
    "Sta": "耐力",
    "Armor": "护甲",
}

# 物品品质数字 → 中文
QUALITY_CN = {
    "0": "粗糙",
    "1": "普通",
    "2": "优秀",
    "3": "精良",
    "4": "史诗",
    "5": "传说",
    "6": "神器",
    "7": "传家宝",
    0: "粗糙",
    1: "普通",
    2: "优秀",
    3: "精良",
    4: "史诗",
    5: "传说",
    6: "神器",
    7: "传家宝",
}
