# -*- coding: utf-8 -*-
"""
WoW 职业专精常量
"""

# 职业 → 专精列表
CLASS_SPEC_MAP = {
    "DeathKnight": ["Blood", "Frost", "Unholy"],
    "DemonHunter": ["Havoc", "Vengeance"],
    "Druid":       ["Balance", "Feral", "Guardian", "Restoration"],
    "Hunter":      ["BeastMastery", "Marksmanship", "Survival"],
    "Mage":        ["Arcane", "Fire", "Frost"],
    "Monk":        ["Brewmaster", "Mistweaver", "Windwalker"],
    "Paladin":     ["Holy", "Protection", "Retribution"],
    "Priest":      ["Discipline", "Holy", "Shadow"],
    "Rogue":       ["Assassination", "Outlaw", "Subtlety"],
    "Shaman":      ["Elemental", "Enhancement", "Restoration"],
    "Warrior":     ["Arms", "Fury", "Protection"],
    "Warlock":     ["Affliction", "Demonology", "Destruction"],
    "Evoker":      ["Augmentation", "Devastation", "Preservation"],
}

# 英文职业名 → 中文
CLASS_CN = {
    "DeathKnight": "死亡骑士",
    "DemonHunter": "恶魔猎手",
    "Druid":       "德鲁伊",
    "Hunter":      "猎人",
    "Mage":        "法师",
    "Monk":        "武僧",
    "Paladin":     "圣骑士",
    "Priest":      "牧师",
    "Rogue":       "潜行者",
    "Shaman":      "萨满祭司",
    "Warrior":     "战士",
    "Warlock":     "术士",
    "Evoker":      "唤魔师",
}

# 英文专精名 → 中文（同名专精只列一次，如 Frost 同时是 DK 和 Mage 的）
SPEC_CN = {
    "Blood":          "鲜血",
    "Frost":          "冰霜",
    "Unholy":         "邪恶",
    "Havoc":          "浩劫",
    "Vengeance":      "复仇",
    "Balance":        "平衡",
    "Feral":          "野性",
    "Guardian":       "守护",
    "Restoration":    "恢复",
    "BeastMastery":   "野兽控制",
    "Marksmanship":   "射击",
    "Survival":       "生存",
    "Arcane":         "奥术",
    "Fire":           "火焰",
    "Brewmaster":     "酒仙",
    "Mistweaver":     "织雾",
    "Windwalker":     "踏风",
    "Holy":           "神圣",
    "Protection":     "防护",
    "Retribution":    "惩戒",
    "Discipline":     "戒律",
    "Shadow":         "暗影",
    "Assassination":  "奇袭",
    "Outlaw":         "狂徒",
    "Subtlety":       "敏锐",
    "Elemental":      "元素",
    "Enhancement":    "增强",
    "Arms":           "武器",
    "Fury":           "狂怒",
    "Affliction":     "痛苦",
    "Demonology":     "恶魔学识",
    "Destruction":    "毁灭",
    "Augmentation":   "增辉",
    "Devastation":    "湮灭",
    "Preservation":   "恩护",
}

# (职业, 专精) → 角色
SPEC_ROLE = {
    ("DeathKnight", "Blood"):         "tank",
    ("DeathKnight", "Frost"):         "dps",
    ("DeathKnight", "Unholy"):        "dps",
    ("DemonHunter", "Havoc"):         "dps",
    ("DemonHunter", "Vengeance"):     "tank",
    ("Druid", "Balance"):             "dps",
    ("Druid", "Feral"):               "dps",
    ("Druid", "Guardian"):            "tank",
    ("Druid", "Restoration"):         "healer",
    ("Hunter", "BeastMastery"):       "dps",
    ("Hunter", "Marksmanship"):       "dps",
    ("Hunter", "Survival"):           "dps",
    ("Mage", "Arcane"):               "dps",
    ("Mage", "Fire"):                 "dps",
    ("Mage", "Frost"):                "dps",
    ("Monk", "Brewmaster"):           "tank",
    ("Monk", "Mistweaver"):           "healer",
    ("Monk", "Windwalker"):           "dps",
    ("Paladin", "Holy"):              "healer",
    ("Paladin", "Protection"):        "tank",
    ("Paladin", "Retribution"):       "dps",
    ("Priest", "Discipline"):         "healer",
    ("Priest", "Holy"):               "healer",
    ("Priest", "Shadow"):             "dps",
    ("Rogue", "Assassination"):       "dps",
    ("Rogue", "Outlaw"):              "dps",
    ("Rogue", "Subtlety"):            "dps",
    ("Shaman", "Elemental"):          "dps",
    ("Shaman", "Enhancement"):        "dps",
    ("Shaman", "Restoration"):        "healer",
    ("Warrior", "Arms"):              "dps",
    ("Warrior", "Fury"):              "dps",
    ("Warrior", "Protection"):        "tank",
    ("Warlock", "Affliction"):        "dps",
    ("Warlock", "Demonology"):        "dps",
    ("Warlock", "Destruction"):       "dps",
    ("Evoker", "Augmentation"):       "dps",
    ("Evoker", "Devastation"):        "dps",
    ("Evoker", "Preservation"):       "healer",
}

# (职业, 专精) → Wowhead CDN 图标 URL
SPEC_ICON = {
    ("DeathKnight", "Blood"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_deathknight_bloodpresence.jpg",
    ("DeathKnight", "Frost"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_deathknight_frostpresence.jpg",
    ("DeathKnight", "Unholy"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_deathknight_unholypresence.jpg",
    ("DemonHunter", "Havoc"):         "https://wow.zamimg.com/images/wow/icons/medium/ability_demonhunter_specdps.jpg",
    ("DemonHunter", "Vengeance"):     "https://wow.zamimg.com/images/wow/icons/medium/ability_demonhunter_spectank.jpg",
    ("Druid", "Balance"):             "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_starfall.jpg",
    ("Druid", "Feral"):               "https://wow.zamimg.com/images/wow/icons/medium/ability_druid_catform.jpg",
    ("Druid", "Guardian"):            "https://wow.zamimg.com/images/wow/icons/medium/ability_racial_bearform.jpg",
    ("Druid", "Restoration"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_healingtouch.jpg",
    ("Hunter", "BeastMastery"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_hunter_bestialdiscipline.jpg",
    ("Hunter", "Marksmanship"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_hunter_focusedaim.jpg",
    ("Hunter", "Survival"):           "https://wow.zamimg.com/images/wow/icons/medium/ability_hunter_camouflage.jpg",
    ("Mage", "Arcane"):               "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_magicalsentry.jpg",
    ("Mage", "Fire"):                 "https://wow.zamimg.com/images/wow/icons/medium/spell_fire_firebolt02.jpg",
    ("Mage", "Frost"):                "https://wow.zamimg.com/images/wow/icons/medium/spell_frost_frostbolt02.jpg",
    ("Monk", "Brewmaster"):           "https://wow.zamimg.com/images/wow/icons/medium/monk_stance_drunkenox.jpg",
    ("Monk", "Mistweaver"):           "https://wow.zamimg.com/images/wow/icons/medium/monk_stance_wisdom.jpg",
    ("Monk", "Windwalker"):           "https://wow.zamimg.com/images/wow/icons/medium/monk_stance_whitetiger.jpg",
    ("Paladin", "Holy"):              "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_holybolt.jpg",
    ("Paladin", "Protection"):        "https://wow.zamimg.com/images/wow/icons/medium/ability_paladin_shieldofthetemplar.jpg",
    ("Paladin", "Retribution"):       "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_auraoflight.jpg",
    ("Priest", "Discipline"):         "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_powerwordshield.jpg",
    ("Priest", "Holy"):               "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_guardianspirit.jpg",
    ("Priest", "Shadow"):             "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_shadowwordpain.jpg",
    ("Rogue", "Assassination"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_eviscerate.jpg",
    ("Rogue", "Outlaw"):              "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_waylay.jpg",
    ("Rogue", "Subtlety"):            "https://wow.zamimg.com/images/wow/icons/medium/ability_stealth.jpg",
    ("Shaman", "Elemental"):          "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_lightning.jpg",
    ("Shaman", "Enhancement"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_shaman_improvedstormstrike.jpg",
    ("Shaman", "Restoration"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_magicimmunity.jpg",
    ("Warrior", "Arms"):              "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_savageblow.jpg",
    ("Warrior", "Fury"):              "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_innerrage.jpg",
    ("Warrior", "Protection"):        "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_defensivestance.jpg",
    ("Warlock", "Affliction"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_deathcoil.jpg",
    ("Warlock", "Demonology"):        "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_metamorphosis.jpg",
    ("Warlock", "Destruction"):       "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_rainoffire.jpg",
    ("Evoker", "Augmentation"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_evoker_augmentation.jpg",
    ("Evoker", "Devastation"):        "https://wow.zamimg.com/images/wow/icons/medium/ability_evoker_devastation.jpg",
    ("Evoker", "Preservation"):       "https://wow.zamimg.com/images/wow/icons/medium/ability_evoker_preservation.jpg",
}

# ========== 副本/团本 中文名 ==========

DUNGEON_CN = {
    "Ara-Kara, City of Echoes": "阿拉卡拉，回声之城",
    "City of Threads": "千丝之城",
    "Grim Batol": "格瑞姆巴托",
    "Mists of Tirna Scithe": "塞兹仙林的迷雾",
    "Necrotic Wake": "通灵战潮",
    "Siege of Boralus": "围攻伯拉勒斯",
    "Stonevault": "矶石宝库",
    "The Dawnbreaker": "破晨号",
}

RAID_BOSS_CN = {
    "Ulgrax the Devourer": "吞噬者乌格拉克斯",
    "The Bloodbound Horror": "血缚恐惧",
    "Sikran, Captain of the Sureki": "苏雷吉队长席克拉",
    "Rasha'nan": "拉夏南",
    "Broodtwister Ovi'nax": "虫巢扭曲者欧维纳克斯",
    "Nexus-Princess Ky'veza": "节点女亲王凯威扎",
    "The Silken Court": "蛛丝议会",
    "Queen Ansurek": "安苏雷克女王",
    "Vexie and the Geargrinders": "维克茜和磨轮",
    "Cauldron of Carnage": "残杀战炉",
    "Rik Reverb": "里克·混响",
    "Stix Bunkjunker": "斯提克斯·堆渣",
    "Sprocketmonger Lockenstock": "链齿狂人洛肯斯托克",
    "The One-Armed Bandit": "独臂盗匪",
    "Mug'Zee, Heads of Security": "穆格·兹奇，安保头子",
    "Chrome King Gallywix": "铬金大王加里维克斯",
}
